/**
 * Tailwind CSS Configuration - BibleLessonSpark
 * ==============================================
 * 
 * SSOT ARCHITECTURE (Frontend Drives Backend):
 *   - ALL values reference CSS VARIABLES (injected at runtime by BrandingProvider)
 *   - NO build-time imports for configurable values
 *   - Tailwind generates classes with var() references
 *   - BrandingProvider controls actual values at runtime
 *   
 * Color flow: branding.ts → generateTailwindCSSVariables() → BrandingProvider → CSS Variables → Here
 *   
 * To change ANY value: Edit ONLY src/config/branding.ts
 */

import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      // Uses existing --spacing-xl from branding.ts
      padding: "var(--spacing-xl)",
      screens: {
        // CSS variable - added by PATCH to branding.ts
        "2xl": "var(--container-max-width)",
      },
    },
    extend: {
      colors: {
        // ALL colors reference CSS variables (injected by BrandingProvider from branding.ts)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          light: "hsl(var(--primary-light))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          hover: "hsl(var(--secondary-hover))",
          light: "hsl(var(--secondary-light))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        burgundy: {
          DEFAULT: "hsl(var(--burgundy))",
          light: "hsl(var(--burgundy-light))",
          hover: "hsl(var(--burgundy-hover))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          light: "hsl(var(--destructive-light))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          light: "hsl(var(--success-light))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          light: "hsl(var(--warning-light))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      // Typography - uses existing CSS variables from branding.ts
      fontFamily: {
        sans: ["var(--font-primary)"],
        serif: ["var(--font-secondary)"],
      },
      // Border radius from CSS variables (generated by branding.ts)
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius)",
        sm: "var(--radius-sm)",
      },
      // Animation keyframes - structural, not branding
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        glow: {
          "0%, 100%": { boxShadow: "var(--shadow-glow)" },
          "50%": { boxShadow: "var(--shadow-lg)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      // Animation durations - CSS variables, runtime controlled
      animation: {
        "accordion-down": "accordion-down var(--transition-fast)",
        "accordion-up": "accordion-up var(--transition-fast)",
        glow: "glow var(--transition-slow) infinite",
        shimmer: "shimmer var(--transition-normal) infinite",
      },
      // Box shadows from CSS variables
      boxShadow: {
        glow: "var(--shadow-glow)",
      },
      // Background gradients from CSS variables
      backgroundImage: {
        "gradient-card": "var(--gradient-card)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-primary": "var(--gradient-primary)",
        "gradient-secondary": "var(--gradient-secondary)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
