const fs = require('fs');
const lines = [];
lines.push("// ============================================================================");
lines.push("// SERIES EXPORT CONFIGURATION - SSOT");
lines.push("// Location: src/constants/seriesExportConfig.ts");
lines.push("// Last Updated: 2026-03-06");
lines.push("// ============================================================================");
lines.push("");
lines.push("import { EXPORT_SPACING, EXPORT_FORMATTING } from '@/constants/lessonStructure';");
lines.push("import { BRANDING } from '@/config/branding';");
lines.push("import type { AudienceProfile } from '@/constants/audienceConfig';");
lines.push("import { resolveAudienceProfile } from '@/constants/audienceConfig';");
lines.push("");
lines.push("export { EXPORT_SPACING, EXPORT_FORMATTING };");
lines.push("");
lines.push("export const SERIES_EXPORT_SECTIONS = {");
lines.push("  COVER:           'cover',");
lines.push("  TOC:             'toc',");
lines.push("  INTRO:           'intro',");
lines.push("  LESSONS:         'lessons',");
lines.push("  HANDOUT_BOOKLET: 'handout_booklet',");
lines.push("  BACK_COVER:      'back_cover',");
lines.push("} as const;");
lines.push("");
lines.push("export type SeriesExportSection = typeof SERIES_EXPORT_SECTIONS[keyof typeof SERIES_EXPORT_SECTIONS];");
lines.push("");
lines.push("export const SERIES_EXPORT_FORMATS = {");
lines.push("  DOCX:        'docx',");
lines.push("  PDF:         'pdf',");
lines.push("  BOOKLET_PDF: 'booklet_pdf',");
lines.push("} as const;");
lines.push("");
lines.push("export type SeriesExportFormat = typeof SERIES_EXPORT_FORMATS[keyof typeof SERIES_EXPORT_FORMATS];");
lines.push("");
lines.push("export const SERIES_EXPORT_FORMAT_LABELS: Record<SeriesExportFormat, string> = {");
lines.push("  docx:        'Word Document (.docx)',");
lines.push("  pdf:         'PDF Document (.pdf)',");
lines.push("  booklet_pdf: 'Booklet PDF \u2014 Print & Fold',");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_EXPORT_FORMAT_MIME: Record<SeriesExportFormat, string> = {");
lines.push("  docx:        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',");
lines.push("  pdf:         'application/pdf',");
lines.push("  booklet_pdf: 'application/pdf',");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_EXPORT_FORMAT_EXT: Record<SeriesExportFormat, string> = {");
lines.push("  docx:        '.docx',");
lines.push("  pdf:         '.pdf',");
lines.push("  booklet_pdf: '.pdf',");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_EXPORT_RECOMMENDED_FORMAT: SeriesExportFormat = SERIES_EXPORT_FORMATS.PDF;");
lines.push("");
lines.push("export const SERIES_EXPORT_FORMAT_SUBTITLES: Partial<Record<SeriesExportFormat, string>> = {");
lines.push("  pdf:         'Recommended for printing',");
lines.push("  booklet_pdf: 'Saddle-stitch \u2014 fold & staple',");
lines.push("} as const;");
lines.push("");
lines.push("export interface LayoutDimensions {");
lines.push("  widthDxa:                number;");
lines.push("  heightDxa:               number;");
lines.push("  marginDxa:               number;");
lines.push("  contentWidthDxa:         number;");
lines.push("  bodyFontHalfPt:          number;");
lines.push("  sectionHeaderFontHalfPt: number;");
lines.push("  chapterTitleFontHalfPt:  number;");
lines.push("  padToMultipleOf4?:       boolean;");
lines.push("}");
lines.push("");
lines.push("export const SERIES_LAYOUT_DIMENSIONS: Record<string, LayoutDimensions> = {");
lines.push("  fullpage: {");
lines.push("    widthDxa:                12240,");
lines.push("    heightDxa:               15840,");
lines.push("    marginDxa:               1440,");
lines.push("    contentWidthDxa:         9360,");
lines.push("    bodyFontHalfPt:          EXPORT_SPACING.body.fontHalfPt,");
lines.push("    sectionHeaderFontHalfPt: 28,");
lines.push("    chapterTitleFontHalfPt:  32,");
lines.push("  },");
lines.push("} as const;");
lines.push("");
lines.push("export interface FontConfig {");
lines.push("  id:          string;");
lines.push("  label:       string;");
lines.push("  docxBody:    string;");
lines.push("  docxHeading: string;");
lines.push("}");
lines.push("");
lines.push("export const SERIES_EXPORT_FONT_OPTIONS: FontConfig[] = [");
lines.push("  { id: 'calibri',  label: 'Calibri (Modern)',      docxBody: 'Calibri',           docxHeading: 'Calibri' },");
lines.push("  { id: 'georgia',  label: 'Georgia (Traditional)', docxBody: 'Georgia',           docxHeading: 'Georgia' },");
lines.push("  { id: 'times',    label: 'Times New Roman',       docxBody: 'Times New Roman',   docxHeading: 'Times New Roman' },");
lines.push("  { id: 'arial',    label: 'Arial (Clean)',         docxBody: 'Arial',             docxHeading: 'Arial' },");
lines.push("  { id: 'garamond', label: 'Garamond (Elegant)',    docxBody: 'Garamond',          docxHeading: 'Garamond' },");
lines.push("  { id: 'palatino', label: 'Palatino (Readable)',   docxBody: 'Palatino Linotype', docxHeading: 'Palatino Linotype' },");
lines.push("];");
lines.push("");
lines.push("export interface SeriesExportOptions {");
lines.push("  includeHandoutBooklet:    boolean;");
lines.push("  omitSection8FromChapters: boolean;");
lines.push("  format:                   SeriesExportFormat;");
lines.push("  layout:                   string;");
lines.push("  font:                     string;");
lines.push("  audience_profile?:        AudienceProfile;");
lines.push("}");
lines.push("");
lines.push("export const SERIES_EXPORT_DEFAULT_OPTIONS: SeriesExportOptions = {");
lines.push("  includeHandoutBooklet:    true,");
lines.push("  omitSection8FromChapters: true,");
lines.push("  format:                   SERIES_EXPORT_FORMATS.PDF,");
lines.push("  layout:                   'fullpage',");
lines.push("  font:                     'calibri',");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_PAGE = {");
lines.push("  widthDxa:        12240,");
lines.push("  heightDxa:       15840,");
lines.push("  marginDxa:       1440,");
lines.push("  contentWidthDxa: 9360,");
lines.push("} as const;");
lines.push("");
lines.push("export const FULLPAGE_PDF = {");
lines.push("  width:        612,");
lines.push("  height:       792,");
lines.push("  margin:       72,");
lines.push("  get contentWidth()  { return this.width  - this.margin * 2; },");
lines.push("  get contentHeight() { return this.height - this.margin * 2; },");
lines.push("  get pageBottom()    { return this.height - this.margin; },");
lines.push("} as const;");
lines.push("");
lines.push("export const BOOKLET_PAGE = {");
lines.push("  width:        396,");
lines.push("  height:       612,");
lines.push("  margin:       28.8,");
lines.push("  get contentWidth()  { return this.width  - this.margin * 2; },");
lines.push("  get contentHeight() { return this.height - this.margin * 2; },");
lines.push("} as const;");
lines.push("");
lines.push("export const BOOKLET_SHEET = {");
lines.push("  width:  792,");
lines.push("  height: 612,");
lines.push("} as const;");
lines.push("");
lines.push("export const BOOKLET_TYPOGRAPHY = {");
lines.push("  bodyFontPt:          9.5,");
lines.push("  bodyLineHeight:      1.42,");
lines.push("  subheadFontPt:       10.5,");
lines.push("  sectionLabelFontPt:  7.5,");
lines.push("  lessonNumFontPt:     7.5,");
lines.push("  lessonTitleFontPt:   14,");
lines.push("  passageFontPt:       8.5,");
lines.push("  coverTitleFontPt:    30,");
lines.push("  coverSubtitleFontPt: 13,");
lines.push("  coverMetaFontPt:     8,");
lines.push("  tocHeadingFontPt:    13,");
lines.push("  tocEntryFontPt:      9.5,");
lines.push("  footerFontPt:        6.5,");
lines.push("  handoutTitleFontPt:  12,");
lines.push("  handoutLabelFontPt:  7.5,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_COVER_TYPOGRAPHY = {");
lines.push("  titleFontPt:        24,");
lines.push("  titleFontHalfPt:    48,");
lines.push("  subtitleFontPt:     14,");
lines.push("  subtitleFontHalfPt: 28,");
lines.push("  metaFontPt:         12,");
lines.push("  metaFontHalfPt:     24,");
lines.push("  footerFontPt:       EXPORT_SPACING.footer.fontPt,");
lines.push("  footerFontHalfPt:   EXPORT_SPACING.footer.fontHalfPt,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_CHAPTER_TYPOGRAPHY = {");
lines.push("  chapterLabelFontPt:     11,");
lines.push("  chapterLabelFontHalfPt: 22,");
lines.push("  chapterTitleFontPt:     16,");
lines.push("  chapterTitleFontHalfPt: 32,");
lines.push("  passageFontPt:          10,");
lines.push("  passageFontHalfPt:      20,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_TOC_TYPOGRAPHY = {");
lines.push("  headingFontPt:          16,");
lines.push("  headingFontHalfPt:      32,");
lines.push("  entryFontPt:            EXPORT_SPACING.body.fontPt,");
lines.push("  entryFontHalfPt:        EXPORT_SPACING.body.fontHalfPt,");
lines.push("  entrySpacingAfterTwips: EXPORT_SPACING.paragraph.afterTwips,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_COLORS = {");
lines.push("  coverTitle:     '3D5C3D',");
lines.push("  coverSubtitle:  'B8860B',");
lines.push("  chapterHeading: '3D5C3D',");
lines.push("  tocHeading:     '3D5C3D',");
lines.push("  tocEntry:       EXPORT_SPACING.colors.bodyText,");
lines.push("  handoutHeader:  '3D5C3D',");
lines.push("  backCoverText:  EXPORT_SPACING.colors.metaText,");
lines.push("  hr:             EXPORT_SPACING.colors.hrLine,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_COVER_COPY = {");
lines.push("  subtitle:     'A BibleLessonSpark Curriculum Series',");
lines.push("  teacherLabel: 'Prepared by',");
lines.push("  churchLabel:  'For',");
lines.push("  generatedBy:  'Generated by ' + BRANDING.appName,");
lines.push("  website:      BRANDING.urls.baseUrl,");
lines.push("} as const;");
lines.push("");
lines.push("export const SERIES_INTRO_PLACEHOLDER =");
lines.push("  'This curriculum series was prepared using BibleLessonSpark.com. ' +");
lines.push("  'Each lesson has been crafted to align with your theology profile, age group, and Bible version, ' +");
lines.push("  'providing a consistent and faithful teaching resource for your class. ' +");
lines.push("  'May the Lord use these lessons to encourage growth in His Word.';");
lines.push("");
lines.push("export const SERIES_HANDOUT_COPY = {");
lines.push("  appendixTitle:       'Group Handout Section',");
lines.push("  appendixSubtitle:    'Reproducible handouts for each lesson \u2014 these pages may be freely reproduced for use within your group.',");
lines.push("  handoutHeaderPrefix: 'Lesson',");
lines.push("} as const;");
lines.push("");
lines.push("export const STUDENT_HANDOUT_SECTION_NUMBER = '8';");
lines.push("");
lines.push("export function buildSeriesExportFilename(");
lines.push("  seriesName: string,");
lines.push("  format: SeriesExportFormat");
lines.push("): string {");
lines.push("  const safeName = seriesName");
lines.push("    .replace(/[^a-zA-Z0-9\\s-]/g, '')");
lines.push("    .replace(/\\s+/g, '_')");
lines.push("    .replace(/-+/g, '-')");
lines.push("    .slice(0, 60);");
lines.push("  const date   = new Date().toISOString().slice(0, 10);");
lines.push("  const ext    = SERIES_EXPORT_FORMAT_EXT[format];");
lines.push("  const suffix = format === SERIES_EXPORT_FORMATS.BOOKLET_PDF ? '_Booklet' : '';");
lines.push("  return safeName + suffix + '_' + date + ext;");
lines.push("}");
lines.push("");
lines.push("export const SERIES_EXPORT_PROGRESS_STEPS = [");
lines.push("  { id: 'loading',    label: 'Loading lesson content...' },");
lines.push("  { id: 'cover',      label: 'Building cover page...' },");
lines.push("  { id: 'toc',        label: 'Generating table of contents...' },");
lines.push("  { id: 'lessons',    label: 'Compiling lesson chapters...' },");
lines.push("  { id: 'handouts',   label: 'Assembling handout section...' },");
lines.push("  { id: 'imposing',   label: 'Imposing booklet layout...' },");
lines.push("  { id: 'finalizing', label: 'Finalizing document...' },");
lines.push("] as const;");
lines.push("");
lines.push("export type SeriesExportProgressStepId =");
lines.push("  typeof SERIES_EXPORT_PROGRESS_STEPS[number]['id'];");
lines.push("");
lines.push("export const SERIES_EXPORT_UI = {");
lines.push("  buttonLabel:               'Export Series',");
lines.push("  modalTitle:                'Export Curriculum Series',");
lines.push("  modalSubtitle:             'Compile your series into a printable curriculum document.',");
lines.push("  formatLabel:               'Choose Export Format',");
lines.push("  optionsLabel:              'Document Options',");
lines.push("  handoutBookletLabel:       'Include Group Handout Section',");
lines.push("  handoutBookletDescription: 'Compiles all group handouts into a tear-out appendix. When enabled, individual lesson chapters will not repeat the handout.',");
lines.push("  exportButton:              'Export Series',");
lines.push("  cancelButton:              'Cancel',");
lines.push("  upgradePrompt:             'Upgrade to Personal Plan to export your series as a complete curriculum document.',");
lines.push("  successMessage:            'Your curriculum series has been exported successfully.',");
lines.push("  errorMessage:              'We were unable to export your series. Please try again. If the problem continues, contact support at ' + BRANDING.contact.supportEmail + '.',");
lines.push("  emptySeriesWarning:        'This series does not have any completed lessons yet. Generate at least one lesson before exporting.',");
lines.push("  formatRequiredHint:        'Please select a format to continue.',");
lines.push("  bookletPrintNote:          'The Booklet PDF includes the Group Handout Section. Print double-sided, fold in half, and staple at the spine.',");
lines.push("} as const;");
lines.push("");
lines.push("// ============================================================================");
lines.push("// AUDIENCE TERMINOLOGY RESOLVER");
lines.push("// ============================================================================");
lines.push("");
lines.push("export function resolveExportTerminology(");
lines.push("  audienceProfile?: AudienceProfile");
lines.push("): { assemblyLabel: string; participantLabel: string } {");
lines.push("  const profile = resolveAudienceProfile(audienceProfile);");
lines.push("  return {");
lines.push("    assemblyLabel:    profile.assembly,");
lines.push("    participantLabel: profile.participant,");
lines.push("  };");
lines.push("}");
lines.push("");
const content = lines.join('\n');
fs.writeFileSync('src/constants/seriesExportConfig.ts', content, { encoding: 'utf8' });
console.log('Done - ' + lines.length + ' lines written');
