/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Source: src/constants/concurrencyConfig.ts
 * Generated by scripts/sync-constants.cjs
 */
// ============================================================================
// CONCURRENCY ADMISSION CONTROL -- SINGLE SOURCE OF TRUTH
// ============================================================================
//
// B8 Session 1. Consumed by supabase/functions/_shared/generationAdmission.ts
// via the synced mirror (Rule #23 -- this file is in FILES_TO_SYNC). No cap,
// stale threshold, poll timing, or cooldown duration governed by this file
// may be hardcoded anywhere else: the claim_generation_slot() RPC
// (supabase/migrations/20260719120000_concurrency_admission_control.sql)
// takes ceiling and TTL as parameters supplied by the caller from here --
// it has no defaults of its own.
//
// Design doc: B8_CONCURRENCY_ADMISSION_DESIGN.md, "SESSION 1 PRE-FLIGHT
// RESOLUTIONS" section (Resolution 3). Derivation for the ceiling values
// below is in that session's chat record -- Anthropic's Scale-tier RPM/TPM
// limits (10K RPM / 10M ITPM / 2M OTPM per model, pulled 2026-07-19) do not
// bind at any ceiling under several hundred concurrent calls, so these are
// NOT vendor-limit-derived. They are a deliberate, self-imposed
// cost/blast-radius circuit breaker -- roughly 5x the highest real distinct
// concurrency ever observed in production -- sized to stay invisible to
// legitimate traffic while still bounding worst-case simultaneous spend
// within a single ~100-180s window (the one gap the existing day-scoped
// rate_limits caps in rateLimitConfig.ts / edgeRateLimit.ts can't close).
// Revisit if real traffic ever approaches these numbers.
// ============================================================================

export type ConcurrencySource =
  | 'generate-lesson'
  | 'reshape-lesson'
  | 'generate-devotional'
  | 'generate-parable'
  | 'extract-lesson'
  | 'toolbelt-reflect';

export type ModelBucket = 'default' | 'fallback_parable';
// 'fast' (Haiku, extract-lesson's fast/tagging path) is intentionally NOT a
// key anywhere in this file -- ungated by design. Haiku throughput ceilings
// are typically far higher and this path is cheap/high-volume by design;
// gating it would add complexity for a bucket that was never the risk.

export const CONCURRENCY_CONFIG = {
  // Which shared Anthropic-account bucket each source's gated call draws
  // against. Mirrors the model-sharing reality in modelConfig.ts's
  // ANTHROPIC_MODELS -- 'default' is claude-sonnet-4-6 (5 of 6 sources);
  // 'fallback_parable' is claude-sonnet-4-5-20250929 (generate-parable's
  // primary model AND every other source's fallback model when its own
  // primary is overloaded -- see design doc Phase 1 Section 1 for why
  // these collide under load).
  sourceBucket: {
    'generate-lesson': 'default',
    'reshape-lesson': 'default',
    'generate-devotional': 'default',
    'generate-parable': 'fallback_parable',
    'extract-lesson': 'default',
    'toolbelt-reflect': 'default',
  } satisfies Record<ConcurrencySource, ModelBucket>,

  // Real, derived numbers (see file header) -- NOT tuned against a hard
  // vendor limit, since none binds. Revisit as real traffic grows.
  bucketCeiling: {
    default: 10,
    fallback_parable: 6,
  } satisfies Record<ModelBucket, number>,

  // Stale-slot threshold (seconds), passed to claim_generation_slot() as
  // p_ttl_seconds -- the fixed-TTL sources' values are each source's own
  // RETRY_CONFIG.totalBudgetMs (modelConfig.ts) + a 20s safety margin, so a
  // slot can never be reclaimed while its call could still legitimately be
  // running. generate-lesson's value (Session 2, live) is the crash-only
  // backstop threshold -- under normal operation its slot is kept fresh by
  // the heartbeat renewing expires_at every heartbeat.intervalSeconds, so
  // this number only matters if the heartbeat itself stops (isolate kill).
  staleThresholdSeconds: {
    'generate-lesson': 60,
    'reshape-lesson': 165,
    'generate-devotional': 165,
    'generate-parable': 110,
    'extract-lesson': 120,
    'toolbelt-reflect': 110,
  } satisfies Record<ConcurrencySource, number>,

  // generate-lesson only (Session 2, live). A SEPARATE interval from
  // generate-lesson's own stall-guard timer, sharing only the same 5s
  // cadence -- the stall guard is scoped to Phase 1's SSE read loop only
  // and is cleared once streaming ends, but this slot must survive
  // Phase 2's non-streaming calls too, so it needs its own longer-lived
  // interval (claim -> Phase 1 -> Phase 2 -> release).
  heartbeat: {
    intervalSeconds: 5,
    renewalWindowSeconds: 60,
  },

  // 'queue' polls claim_generation_slot() on a short interval up to
  // maxWaitMs before giving up; 'immediate' rejects on the first failed
  // claim. All 5 Session 1 sources are 'immediate' -- none of their
  // Anthropic budgets (RETRY_CONFIG.totalBudgetMs) have slack to carve a
  // wait out of. generate-lesson (Session 2, live) is 'queue' -- it
  // streams, so the wait happens invisibly inside the already-open SSE
  // connection, before any tokens, indistinguishable to the teacher from
  // ordinary "preparing your lesson" time.
  admissionPolicy: {
    'generate-lesson': 'queue',
    'reshape-lesson': 'immediate',
    'generate-devotional': 'immediate',
    'generate-parable': 'immediate',
    'extract-lesson': 'immediate',
    'toolbelt-reflect': 'immediate',
  } satisfies Record<ConcurrencySource, 'queue' | 'immediate'>,

  // generate-lesson's bounded poll-for-a-slot window (live, Session 2 --
  // consulted only when admissionPolicy is 'queue', currently just
  // generate-lesson).
  admissionQueue: {
    pollIntervalMs: 2_000,
    maxWaitMs: 25_000,
  },

  // Shared cooldown window applied to a model_bucket when the retry layer
  // (_shared/anthropicRetry.ts) exhausts retries/fallback on 'overloaded'
  // or 'rate_limit'. Extended forward (GREATEST), never reset backward, on
  // repeated signals. Writer live as of Session 2, wired only into
  // generate-lesson's own call sites (anthropicRetry.ts's giveUp() checks
  // for an optional supabase+modelBucket pair that only generate-lesson
  // currently passes) -- the 5 Session 1 functions still READ this value
  // on every claim (so they'll respect a cooldown generate-lesson sets),
  // they just don't WRITE one themselves yet. Documented follow-up, not
  // an oversight: adding the same two options-object fields to their
  // existing callAnthropicNonStreaming() calls closes the gap whenever
  // that's wanted -- no anthropicRetry.ts changes needed for it.
  cooldownSeconds: 20,
} as const;
