/**
 * âš ï¸  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * This file is automatically generated from the frontend SSOT.
 * Source: src/constants/lessonStructure.ts
 * 
 * To make changes:
 * 1. Edit the source file in src/constants/
 * 2. Run: npm run sync-constants
 * 3. Commit both files (frontend source + backend mirror)
 * 
 * Generated: 2025-11-24T15:09:55.570Z
 * Generator: scripts/sync-constants.cjs
 * Architecture: Frontend Drives Backend (Master Vision Principle)
 */

/**
 * LessonSparkUSA Constants - Lesson Structure
 *
 * SINGLE SOURCE OF TRUTH for the 12-section lesson structure.
 * This is Tier 1 (Supreme/Foundational) - UNCHANGING.
 *
 * GOVERNANCE: Only admin can modify these constants.
 * Changes here affect every lesson generated.
 *
 * @version 1.0.0
 * @lastUpdated 2025-11-21
 */

import type { LessonSection, LessonStructure } from './contracts';

// ============================================================
// LESSON STRUCTURE VERSION
// ============================================================

export const LESSON_STRUCTURE_VERSION = '1.0.0';

// ============================================================
// THE 12-SECTION LESSON STRUCTURE
// ============================================================

export const LESSON_SECTIONS: LessonSection[] = [
  {
    id: 1,
    name: "Lesson Overview",
    description: "Brief summary of the lesson's main theme and purpose",
    required: true,
    targetWordCount: 150,
    requiredElements: ["Main theme statement", "Key takeaway", "Target audience consideration"]
  },
  {
    id: 2,
    name: "Learning Objectives",
    description: "Clear, measurable goals for what students will learn",
    required: true,
    targetWordCount: 100,
    requiredElements: ["3-5 specific objectives", "Action verbs", "Measurable outcomes"]
  },
  {
    id: 3,
    name: "Key Scripture Passages",
    description: "Primary and supporting Bible verses for the lesson",
    required: true,
    targetWordCount: 200,
    requiredElements: ["Primary passage with full text", "Supporting verses", "Context notes"]
  },
  {
    id: 4,
    name: "Theological Background",
    description: "Doctrinal context and historical background",
    required: true,
    targetWordCount: 300,
    requiredElements: ["Historical context", "Theological significance", "Denominational perspective"]
  },
  {
    id: 5,
    name: "Opening Activities",
    description: "Engaging activities to introduce the lesson topic",
    required: true,
    targetWordCount: 200,
    requiredElements: ["Icebreaker or hook", "Connection to main theme", "Time estimate"]
  },
  {
    id: 6,
    name: "Main Teaching Content",
    description: "Core biblical teaching and exposition",
    required: true,
    targetWordCount: 500,
    requiredElements: ["Verse-by-verse or thematic exposition", "Key points", "Illustrations"]
  },
  {
    id: 7,
    name: "Interactive Activities",
    description: "Hands-on activities to reinforce learning",
    required: true,
    targetWordCount: 250,
    requiredElements: ["Age-appropriate activities", "Materials needed", "Instructions"]
  },
  {
    id: 8,
    name: "Discussion Questions",
    description: "Thought-provoking questions for group discussion",
    required: true,
    targetWordCount: 150,
    requiredElements: ["5-7 questions", "Mix of factual and application", "Follow-up prompts"]
  },
  {
    id: 9,
    name: "Life Applications",
    description: "Practical ways to apply the lesson to daily life",
    required: true,
    targetWordCount: 200,
    requiredElements: ["Real-world scenarios", "Personal challenges", "Weekly action steps"]
  },
  {
    id: 10,
    name: "Assessment Methods",
    description: "Ways to evaluate student understanding",
    required: true,
    targetWordCount: 150,
    requiredElements: ["Informal assessment ideas", "Review questions", "Observable outcomes"]
  },
  {
    id: 11,
    name: "Student Handout",
    description: "Reproducible handout for students to take home",
    required: true,
    targetWordCount: 300,
    requiredElements: ["Key points summary", "Scripture references", "Take-home questions", "Space for notes"]
  },
  {
    id: 12,
    name: "Teacher Preparation Notes",
    description: "Guidance for teacher preparation and delivery",
    required: true,
    targetWordCount: 200,
    requiredElements: ["Preparation checklist", "Materials list", "Teaching tips", "Prayer focus"]
  }
];

// ============================================================
// STRUCTURE WRAPPER
// ============================================================

export const LESSON_STRUCTURE: LessonStructure = {
  version: LESSON_STRUCTURE_VERSION,
  sections: LESSON_SECTIONS
};

// ============================================================
// COMPUTED VALUES
// ============================================================

export const TOTAL_TARGET_WORD_COUNT = LESSON_SECTIONS.reduce(
  (sum, section) => sum + section.targetWordCount,
  0
);
