/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Source: src/constants/modelConfig.ts
 * Generated by scripts/sync-constants.cjs
 */
// ============================================================================
// ANTHROPIC MODEL IDS -- SINGLE SOURCE OF TRUTH
// ============================================================================
//
// Every Anthropic model id used by any generator lives HERE and nowhere else.
// Edge functions import the synced mirror from '../_shared/modelConfig.ts'
// (auto-generated by scripts/sync-constants.cjs -- never hand-edit the mirror).
//
// Rationale: on 2026-06-15 Anthropic retired claude-sonnet-4-20250514 with no
// grace period, and that literal was duplicated across six edge functions. Each
// had to be hunted down and swapped by hand while generation was down. With one
// authoritative map, the next migration is a single edit here plus a re-sync
// and redeploy.
//
//   default -- full lessons, reshape, devotionals, extract default paths, toolbelt
//   fast    -- extract-lesson fast extraction paths (cheap, high-volume)
//   parable -- generate-parable. Intentionally pinned to 4.5; do NOT collapse to
//              default -- parable quality was tuned against this model.
// ============================================================================

export const ANTHROPIC_MODELS = {
  default: 'claude-sonnet-4-6',
  fast: 'claude-haiku-4-5-20251001',
  parable: 'claude-sonnet-4-5-20250929',
} as const;

export type AnthropicModelKey = keyof typeof ANTHROPIC_MODELS;