// ============================================================================
// BACKEND MIRROR: Organization Configuration
// SYNCED FROM: src/constants/organizationConfig.ts
// DO NOT EDIT THIS FILE - Edit the frontend SSOT and sync
// ============================================================================

// ----------------------------------------------------------------------------
// ORGANIZATION TYPES
// ----------------------------------------------------------------------------

export const ORG_TYPES = {
  beta_program: {
    id: 'beta_program',
    label: 'Beta Program',
    description: 'Beta testing program organization',
    allowSubOrgs: false,
    rateLimit: { lessonsPerDay: 3 },
  },
  church: {
    id: 'church',
    label: 'Church',
    description: 'Local church organization',
    allowSubOrgs: true,
    rateLimit: null,
  },
  enterprise: {
    id: 'enterprise',
    label: 'Enterprise',
    description: 'Convention, association, or large organization',
    allowSubOrgs: true,
    rateLimit: null,
  },
} as const;

export type OrgType = keyof typeof ORG_TYPES;

export const ORG_TYPE_IDS = Object.keys(ORG_TYPES) as OrgType[];

// ----------------------------------------------------------------------------
// BETA ACCESS LEVELS
// ----------------------------------------------------------------------------

export const BETA_ACCESS_LEVELS = {
  private: {
    id: 'private',
    label: 'Private Beta',
    description: 'Invitation only - admin must approve',
    openEnrollment: false,
  },
  public: {
    id: 'public',
    label: 'Public Beta',
    description: 'Open enrollment - anyone can join',
    openEnrollment: true,
  },
} as const;

export type BetaAccessLevel = keyof typeof BETA_ACCESS_LEVELS;

export const BETA_ACCESS_LEVEL_IDS = Object.keys(BETA_ACCESS_LEVELS) as BetaAccessLevel[];

// ----------------------------------------------------------------------------
// ORGANIZATION HIERARCHY
// ----------------------------------------------------------------------------

export const ORG_HIERARCHY = {
  maxDepth: 2,
  levelNames: {
    1: 'Organization',
    2: 'Sub-Organization',
  } as Record<number, string>,
} as const;

// ----------------------------------------------------------------------------
// VALIDATION FUNCTIONS
// ----------------------------------------------------------------------------

export const isValidOrgType = (type: string): type is OrgType => {
  return type in ORG_TYPES;
};

export const isValidBetaAccessLevel = (level: string): level is BetaAccessLevel => {
  return level in BETA_ACCESS_LEVELS;
};

export const canHaveSubOrgs = (type: OrgType): boolean => {
  return ORG_TYPES[type].allowSubOrgs;
};

export const isWithinMaxDepth = (parentLevel: number): boolean => {
  return parentLevel < ORG_HIERARCHY.maxDepth;
};

export const getOrgLevel = (parentOrgId: string | null, parentLevel?: number): number => {
  if (!parentOrgId) return 1;
  return (parentLevel ?? 1) + 1;
};

// ----------------------------------------------------------------------------
// PLATFORM MODE BEHAVIOR
// ----------------------------------------------------------------------------

export const PLATFORM_MODE_ACCESS = {
  private_beta: {
    allowedOrgTypes: ['beta_program'] as OrgType[],
    allowedBetaLevels: ['private'] as BetaAccessLevel[],
    requiresOrgMembership: true,
    tierEnforcement: false,
    allSectionsForAll: true,
  },
  public_beta: {
    allowedOrgTypes: ['beta_program'] as OrgType[],
    allowedBetaLevels: ['private', 'public'] as BetaAccessLevel[],
    requiresOrgMembership: true,
    tierEnforcement: false,
    allSectionsForAll: true,
  },
  production: {
    allowedOrgTypes: ['beta_program', 'church', 'enterprise'] as OrgType[],
    allowedBetaLevels: ['private', 'public'] as BetaAccessLevel[],
    requiresOrgMembership: false,
    tierEnforcement: true,
    allSectionsForAll: false,
  },
} as const;

export type PlatformMode = keyof typeof PLATFORM_MODE_ACCESS;

// ----------------------------------------------------------------------------
// ORG LESSON POOL -- 30-DAY ROLLING ALLOWANCE (SSOT mirror)
// ----------------------------------------------------------------------------
// The Shepherding org pool is a 30-DAY allowance. It REFILLS to full every
// periodDays, INDEPENDENT of the annual Stripe billing boundary. No carryover.
// Rolled lazily on read by generate-lesson / reshape-lesson; no pg_cron, no
// DB trigger (Architecture Principle #2). periodDays is the ONE source of the
// window length; never hardcode a day count inside an edge function.
// ----------------------------------------------------------------------------

export const ORG_POOL = {
  /** Length of the rolling pool window, in days. On refill, usage resets to 0. */
  periodDays: 30,
} as const;

// ----------------------------------------------------------------------------
// LESSON FUNDING DECLARATION (SSOT mirror) -- which bucket a gen/reshape charges
// ----------------------------------------------------------------------------
// FRONTEND DRIVES BACKEND: an affiliated member DECLARES the funding bucket at
// lesson initiation. The backend VALIDATES against these values and never
// invents the target. The charge is LOCKED to this declaration at generation
// time; the post-generation View checkbox only changes sharing visibility.
//   personal -> the member's personal allowance (free trial or paid)
//   shepherd -> the organization (Shepherding) pool
// ----------------------------------------------------------------------------

export const LESSON_FUNDING = {
  personal: 'personal',
  shepherd: 'shepherd',
} as const;

export type LessonFunding = typeof LESSON_FUNDING[keyof typeof LESSON_FUNDING];

/**
 * Safe default when a request omits a funding declaration: charge PERSONAL,
 * so the shared Shepherd pool is never drawn unintentionally.
 */
export const DEFAULT_LESSON_FUNDING: LessonFunding = LESSON_FUNDING.personal;

export const isValidLessonFunding = (value: unknown): value is LessonFunding =>
  value === LESSON_FUNDING.personal || value === LESSON_FUNDING.shepherd;
