// ============================================================
// LESSONSPARK USA - PRICING CONFIGURATION (BACKEND SSOT)
// Location: supabase/functions/_shared/pricingConfig.ts
//
// ⚠️ DO NOT EDIT THIS FILE DIRECTLY
// This is auto-synced from src/constants/pricingConfig.ts
// Run: npm run sync-constants
// ============================================================

// Tier type - matches database enum
export type SubscriptionTier = 'free' | 'personal' | 'admin';

// Section mappings - SSOT for tier-based access
export const TIER_SECTIONS = {
  free: ['1', '5', '8'],
  personal: ['1', '2', '3', '4', '5', '6', '7', '8'],
  admin: ['1', '2', '3', '4', '5', '6', '7', '8'],
} as const;

// Free tier sections as numbers (for comparison/display logic)
export const FREE_TIER_SECTION_NUMBERS = [1, 5, 8] as const;

// Full tier sections as numbers (for lessonTiers.ts import)
export const FULL_TIER_SECTION_NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8] as const;

// Helper function to get sections for a tier
export function getTierSections(tier: SubscriptionTier): string[] {
  return [...TIER_SECTIONS[tier]];
}

// Helper to convert string sections to numbers
export function getTierSectionsAsNumbers(tier: SubscriptionTier): number[] {
  return TIER_SECTIONS[tier].map(s => parseInt(s, 10));
}
