/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Source: src/constants/rateLimitConfig.ts
 * Generated by scripts/sync-constants.cjs
 */
/**
 * WARNING: DEPRECATED -- DO NOT ACTIVATE AS-IS.
 * This module is NOT wired into generate-lesson and has NO tier/paid/admin awareness.
 * Activating it would cap PAID users regardless of tier (e.g. throttle a 120- or 250-lesson
 * plan at a flat limit). The LIVE limit system is the check_lesson_limit RPC plus the free
 * trial counters in trialConfig.ts -- modify those, not this file.
 */
// =============================================================================
// RATE LIMIT CONSTANTS
// SSOT MASTER: Frontend rate limit definitions
// Backend mirror: supabase/functions/_shared/rateLimit.ts
// =============================================================================

/**
 * Rate limit configuration for lesson generation
 * Controls API usage and costs
 */
export const RATE_LIMITS = {
  // Beta program limits
  BETA_LESSONS_PER_DAY: 7,
  BETA_PERIOD_HOURS: 24,
  
  // Production limits (post-beta)
  FREE_LESSONS_PER_DAY: 3,
  FREE_PERIOD_HOURS: 24,
  
  // Admin exempt from limits
  ADMIN_EXEMPT: true,
} as const;

/**
 * Rate limit error messages
 */
export const RATE_LIMIT_MESSAGES = {
  BETA_EXCEEDED: (resetTime: string) => 
    `Beta rate limit reached: Maximum ${RATE_LIMITS.BETA_LESSONS_PER_DAY} lessons per ${RATE_LIMITS.BETA_PERIOD_HOURS} hours. Try again at ${resetTime}.`,
  FREE_EXCEEDED: (resetTime: string) => 
    `Daily limit reached: Maximum ${RATE_LIMITS.FREE_LESSONS_PER_DAY} lessons per day. Upgrade for unlimited lessons or try again at ${resetTime}.`,
} as const;

export type RateLimitTier = 'beta' | 'free' | 'paid' | 'admin';
