/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Source: src/constants/theologyProfiles.ts
 * Generated by scripts/sync-constants.cjs
 */
import type { TheologyProfileId, SecurityDoctrine, TulipStance } from './contracts';

/**
 * THEOLOGY PROFILES - Single Source of Truth (SSOT)
 * 
 * This file defines all Baptist theology profiles for BibleLessonSpark.
 * 
 * ARCHITECTURE:
 * - `summary`: User-facing description (shown in UI)
 * - `filterContent`: Full theological filter (backend only - injected into AI prompt)
 * - `avoidTerminology`: Terms that MUST NOT appear in generated lessons
 * - `preferredTerminology`: Substitutions for avoided terms
 * - `requiredTerminology`: Terms that MUST appear (Reformed/Primitive only)
 * - `guardrails`: Explicit content prohibitions
 * 
 * DISPLAY ORDER: As specified by product owner
 * DEFAULT PROFILE: Baptist Core Beliefs
 *
 * Updated: January 2026
 *
 * CRITICAL TERMINOLOGY FIX (January 2026):
 * - ALL profiles EXCEPT Reformed Baptist now prohibit "sacrament", "sacraments", "Eucharist"
 * - Baptists use "ordinance" (not "sacrament") and "Lord's Supper" (not "Eucharist")
 * - Reformed Baptists MAY use sacramental language due to their confessional heritage (1689 LBCF)
 */

// ============================================================================
// INTERFACES
// ============================================================================

export interface TheologyProfile {
  id: TheologyProfileId;
  name: string;
  shortName: string;
  displayOrder: number;
  isDefault: boolean;
  summary: string; // USER-FACING - shown in UI
  filterContent: string; // BACKEND ONLY - injected into AI prompt
  avoidTerminology: string[];
  preferredTerminology: Record<string, string>;
  requiredTerminology: string[];
  guardrails: string[];
  securityDoctrine: SecurityDoctrine;
  tulipStance: TulipStance;
  badgeClass: string;
}

// ============================================================================
// THEOLOGY PROFILES DATA
// ============================================================================

export const THEOLOGY_PROFILES: TheologyProfile[] = [
  // -------------------------------------------------------------------------
  // 1. BAPTIST CORE BELIEFS - DEFAULT
  // -------------------------------------------------------------------------
  {
    id: "baptist-core-beliefs",
    name: "Baptist Core Beliefs",
    shortName: "Core",
    displayOrder: 1,
    isDefault: true,
    summary: "All Baptists affirm the authority of Scripture, salvation by grace through faith in Christ, believer's baptism by immersion, the autonomy of the local church, two symbolic ordinances, evangelistic responsibility, moral living, and the future return of Christ.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200',
    avoidTerminology: [
      // Avoid ALL disputed terminology - Calvinist
      "Total Depravity",
      "Total Inability",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "meticulous sovereignty",
      "determinism",
      "covenant theology",
      "perseverance of the saints",
      // Avoid ALL disputed terminology - Arminian
      "prevenient grace",
      "conditional security",
      "can lose salvation",
      "apostasy",
      // Avoid disputed church order
      "complementarianism",
      "egalitarianism",
      "regulative principle",
      // Avoid disputed practices
      "foot washing as ordinance",
      "charismatic gifts",
      "tongues",
      "prophecy as normative",
      // Avoid disputed mission stances
      "anti-mission",
      "mission boards",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "humanity has fallen into sin",
      "election": "God's saving purpose in Christ",
      "atonement": "Christ's death and resurrection are the basis of salvation",
      "grace": "salvation is by grace through faith",
      "security": "believers are kept by God's power",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Promotes any specific point of Calvinism",
      "Promotes Arminianism or conditional security",
      "Takes a position on complementarianism or egalitarianism",
      "Advocates the regulative principle or charismatic gifts",
      "Presents foot washing as a required ordinance",
      "Takes a position on mission boards or anti-mission stances",
      "Includes any denominational non-shared emphasis",
      "Takes sides on disputed Baptist doctrines"
    ],
    filterContent: `## THEOLOGICAL LENS: Baptist Core Beliefs

This profile represents the universally shared theological commitments held by ALL major Baptist traditions. Nothing appears unless every Baptist group affirms it.

### Scripture
The Bible is the inspired, authoritative, trustworthy Word of God. Scripture is the final rule of faith and practice. No additional inspired books, revelations, or authorities are recognized.

### God
There is one God, revealed eternally as Father, Son, and Holy Spirit. God is holy, righteous, loving, all-powerful, and all-knowing. God is the Creator and Sustainer of all things.

### Humanity & Sin
All people are created in the image of God and possess inherent worth. Humanity has fallen into sin and is unable to reconcile itself to God. Every person needs salvation through Jesus Christ.

### Salvation
Salvation is by grace through faith in Jesus Christ alone. Christ's death and resurrection are the only basis of salvation. Individuals must personally repent and believe to be saved. Regeneration, forgiveness, and new life are the work of God, not human merit.

### Christ
Jesus Christ is fully God and fully man. He lived a sinless life, died a substitutionary death, and rose bodily from the grave. Christ is the only Savior and mediator. He will return visibly and bodily.

### Holy Spirit
The Holy Spirit convicts of sin, regenerates, indwells, guides, and empowers believers. He produces spiritual growth, godly character, and obedience to Christ.

### Church
The local church is the primary, biblical expression of the body of Christ. Churches are autonomous, self-governing under Christ. Membership consists of regenerate believers. All Baptists affirm the priesthood of all believers.

### Ordinances
Two ordinances instituted by Christ:
1. Baptism: administered only to believers, by immersion, symbolizing union with Christ
2. Lord's Supper: a symbolic memorial of Christ's sacrifice

### Worship
Worship must be biblical, Christ-centered, and reverent. Scripture reading and preaching are central.

### Missions & Evangelism
Every Baptist tradition affirms the responsibility to share the gospel with all people. Evangelism is both personal and congregational. Missions are essential to Baptist identity.

### Ethics
Believers are called to live holy, obedient, and morally upright lives. Marriage is between one man and one woman. Human life is sacred.

### Eschatology
Jesus Christ will return bodily and visibly. There will be a final judgment. The dead will be resurrected. Heaven and Hell are real and eternal.

### Tone
Warm, biblical, Christ-centered, and accessible. Avoid doctrinal positions not universally held among Baptists. Emphasize unity in the essentials.

### CRITICAL INSTRUCTION
This profile must EXCLUDE all doctrines not unanimously affirmed across Baptist traditions. Stay neutral on: election debates, security debates, church polity details, worship style, spiritual gifts, and any denominational-specific emphases.`
  },

  // -------------------------------------------------------------------------
  // 2. SOUTHERN BAPTIST (BF&M 1963)
  // -------------------------------------------------------------------------
  {
    id: "southern-baptist-bfm-1963",
    name: "Southern Baptist (BF&M 1963)",
    shortName: "SBC 1963",
    displayOrder: 2,
    isDefault: false,
    summary: "A Christ-centered, Scripture-authoritative, evangelistic, missions-minded Southern Baptist doctrinal identity emphasizing universal atonement, human responsibility, believer's baptism, congregational autonomy, eternal security, warm worship, and strong personal discipleship--interpreted through the lens of Christ as the criterion of Scripture.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-primary-light text-primary border-primary/20',
    avoidTerminology: [
      "Total Depravity",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect" ,
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "predestined individuals",
      "meticulous sovereignty",
      "determinism",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity / sinful nature",
      "Unconditional Election": "election consistent with foreknowledge and human responsibility",
      "Limited Atonement": "Christ died for all / unlimited atonement",
      "Irresistible Grace": "the Spirit draws and convicts; individuals may respond or resist",
      "regeneration precedes faith": "faith and repentance precede regeneration",
      "the elect": "believers / those who trust in Christ",
      "Effectual Calling": "the Spirit's conviction and drawing",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Promotes unconditional election or irresistible grace as doctrinal fact",
      "Imposes BF&M 2000-style complementarian restrictions",
      "Suggests charismatic gifts are normative",
      "Undermines believer's baptism or congregational polity",
      "Uses coercive evangelism or manipulative decisionism",
      "Adopts liberal theology, universalism, or moral revisionism",
      "Uses TULIP terminology or Calvinist/Reformed language",
      "Suggests humans cannot genuinely respond to the gospel"
    ],
    filterContent: `## THEOLOGICAL LENS: Southern Baptist (BF&M 1963)

### Scripture
Scripture is inspired, authoritative, trustworthy, and sufficient. Jesus Christ is the criterion by which the Bible is to be interpreted. Use literal-historical-grammatical interpretation with Christ-centered hermeneutics.

### God
God is sovereign, holy, righteous, loving, and personal. His sovereignty includes providential care without requiring deterministic outcomes. God desires the salvation of all and works through human freedom and responsibility.

### Salvation
- Election is taught but not defined deterministically; usually understood in foreknowledge-based or corporate terms
- Universal provision, personal application: Christ died for all; salvation becomes effective through repentance and faith
- Grace draws and convicts but can be resisted
- Faith and repentance precede the experience of regeneration
- Eternal Security: those truly saved are kept by God's power

### Holy Spirit
The Spirit convicts, regenerates, indwells, sanctifies, and empowers believers. Non-charismatic: miraculous gifts are not normative for the church today.

### Church
Local church autonomy; congregational governance. BF&M 1963 is less explicit on gender roles--traditional male pastoral leadership is customary.

### Ethics
Holiness, obedience, prayer, service, and Christlike character expected. Marriage traditionally between one man and one woman. Life is sacred from conception.

### Tone
Warm, pastoral, Christ-centered, Scripture-rooted. Emphasize soul competency, Christian liberty, and personal devotion. Avoid heavy confessional Reformed terminology or deterministic framing.`
  },

  // -------------------------------------------------------------------------
  // 3. SOUTHERN BAPTIST (BF&M 2000)
  // -------------------------------------------------------------------------
  {
    id: "southern-baptist-bfm-2000",
    name: "Southern Baptist (BF&M 2000)",
    shortName: "SBC 2000",
    displayOrder: 3,
    isDefault: false,
    summary: "A conservative, Scripture-authoritative, complementarian, evangelistic Southern Baptist doctrinal framework emphasizing biblical inerrancy, universal atonement, salvation by grace through faith, believer's baptism, eternal security, global missions, moral clarity, and congregational autonomy -- shaped by the official Baptist Faith & Message (2000).",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-primary-light text-primary border-primary/20',
    avoidTerminology: [
      "Total Depravity",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "predestined individuals",
      "meticulous sovereignty",
      "determinism",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity / sinful nature",
      "Unconditional Election": "election consistent with foreknowledge and human responsibility",
      "Limited Atonement": "Christ died for all / unlimited atonement",
      "Irresistible Grace": "the Spirit draws and convicts; individuals may respond or resist",
      "regeneration precedes faith": "faith and repentance precede regeneration",
      "the elect": "believers / those who trust in Christ",
      "Effectual Calling": "the Spirit's conviction and drawing",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Rejects complementarianism or affirms women as pastors",
      "Promotes unconditional election and irresistible grace as required SBC doctrine",
      "Suggests charismatic gifts are normative in SBC churches",
      "Undermines believer's baptism or congregational polity",
      "Accepts liberal theological reinterpretations",
      "Embraces universalism or moral revisionism",
      "Uses TULIP terminology or Calvinist/Reformed language",
      "Suggests humans cannot genuinely respond to the gospel"
    ],
    filterContent: `## THEOLOGICAL LENS: Southern Baptist (BF&M 2000)

### Scripture
The Bible is inerrant, infallible, fully trustworthy, authoritative, and sufficient. Interpreted using historical-grammatical hermeneutics. Scripture is the final authority. No reinterpretation through culture, critical theory, or modernist frameworks.

### God
God is sovereign, holy, righteous, loving, and all-powerful. His sovereignty does not imply determinism but includes divine foreknowledge and purposeful governance. God desires salvation for all, yet salvation is only for those who believe.

### Salvation
- Election is biblical but understood within God's foreknowledge and human responsibility
- Christ's death is sufficient for all, efficient only for believers (unlimited atonement)
- Grace draws and convicts but can be resisted
- Repentance and faith precede regeneration in human experience
- Perseverance/Eternal Security: those truly saved are kept by God and will persevere

### Holy Spirit
The Spirit convicts, regenerates, indwells, sanctifies, and empowers believers. Non-charismatic normative stance: sign gifts are not required or expected. No new revelation beyond Scripture.

### Church
Local church autonomy and congregational governance. Complementarianism: "The office of pastor is limited to men as qualified by Scripture." Cooperative Program missions are voluntary.

### Ethics
Marriage is exclusively between one man and one woman. Family roles reflect complementarianism. Sanctity of human life from conception. Rejects pornography, sexual immorality, drunkenness, gambling.

### Tone
Biblical, doctrinally clear, conservative, evangelistic. Accuracy, clarity, and pastoral warmth required. Avoid academic abstraction and hyper-Calvinistic determinism.`
  },

  // -------------------------------------------------------------------------
  // 4. NATIONAL BAPTIST CONVENTION (USA)
  // -------------------------------------------------------------------------
  {
    id: "national-baptist-convention",
    name: "National Baptist Convention (USA)",
    shortName: "NBC",
    displayOrder: 4,
    isDefault: false,
    summary: "A warm, evangelistic, Scripture-rooted, Christ-centered Baptist doctrinal identity emphasizing universal atonement, genuine human freedom, believer's baptism, congregational autonomy, strong community witness, expressive worship, moral integrity, and holistic Christian mission (personal salvation + community transformation).",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    avoidTerminology: [
      "Total Depravity",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "meticulous sovereignty",
      "determinism",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity / sinful nature",
      "Unconditional Election": "election understood in foreknowledge-based or corporate terms",
      "Limited Atonement": "Christ died for the sins of the whole world",
      "Irresistible Grace": "grace calls, convicts, enables--but does not coerce",
      "regeneration precedes faith": "faith and repentance precede conversion",
      "the elect": "believers / those who trust in Christ",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Promotes Calvinistic unconditional election or irresistible grace",
      "Suggests charismatic gifts as normative for worship",
      "Denies the authority or sufficiency of Scripture",
      "Undermines believer's baptism or congregational autonomy",
      "Teaches universalism, works-based salvation, prosperity gospel, or liberal theology that rejects biblical ethics",
      "Minimizes the moral teachings of Scripture",
      "Uses TULIP terminology or Calvinist/Reformed language"
    ],
    filterContent: `## THEOLOGICAL LENS: National Baptist Convention (USA)

### Scripture
The Bible is inspired, inerrant in its original manuscripts, authoritative, and sufficient. Interpreted with a strong emphasis on justice, community responsibility, and faithful Christian living.

### God
God is sovereign, omniscient, omnipotent, holy, just, and loving. God's sovereignty works in harmony with human moral responsibility. God desires all to come to repentance and salvation.

### Salvation
- Election is understood in foreknowledge-based or corporate terms; rejects Calvinistic unconditional election
- Unlimited Atonement: Christ died for the sins of the whole world
- Grace calls, convicts, enables, and empowers--but does not coerce
- Faith and repentance precede conversion
- Eternal Security is widely held; emphasis on living faith and obedience as marks of genuine salvation

### Holy Spirit
The Spirit convicts, regenerates, sanctifies, comforts, empowers, and unifies the church. Non-charismatic as a rule, but often exhibits expressive worship empowered by the Spirit.

### Church
Strong congregational autonomy. Emphasis on fellowship, community empowerment, discipleship, and service. The church is a spiritual family and a center of community life.

### Ethics
Strong emphasis on holiness, moral purity, family life, community responsibility, justice, mercy, and compassion. Marriage between one man and one woman. Sanctity of human life.

### Worship
Worship is expressive, joyful, reverent, Christ-honoring, featuring dynamic preaching, congregational singing, gospel music, testimonies, and celebratory praise.

### Tone
Warm, pastoral, inspirational, biblically grounded. Emphasize hope, encouragement, empowerment, and faithful Christian living. Avoid academic abstraction.`
  },

  // -------------------------------------------------------------------------
  // 5. INDEPENDENT BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "independent-baptist",
    name: "Independent Baptist",
    shortName: "IB",
    displayOrder: 5,
    isDefault: false,
    summary: "A conservative, evangelistic, dispensational, non-charismatic doctrinal baseline emphasizing Scripture authority, unlimited atonement, personal decision for Christ, eternal security, believer's baptism, local church autonomy, and strong separation from secular values.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-blue-100 text-blue-800 border-accent/50',
    avoidTerminology: [
      "Total Depravity",
      "Total Inability",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "meticulous sovereignty",
      "determinism",
      "covenant theology",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity capable of responding to God's conviction",
      "Unconditional Election": "election based on foreknowledge / whosoever will may come",
      "Limited Atonement": "Christ died for the sins of all people everywhere",
      "Irresistible Grace": "the Spirit convicts, but grace is resistible",
      "regeneration precedes faith": "regeneration follows faith and repentance",
      "the elect": "believers / those who have trusted Christ",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Suggests predestination removes human responsibility",
      "Promotes Calvinistic unconditional election or irresistible grace",
      "Advocates charismatic gifts as normative",
      "Undermines dispensational distinctions or the doctrine of a literal Second Coming",
      "Introduces liberal theology, universal salvation, or cultural reinterpretation of Scripture",
      "Suggests loss of salvation or works-based salvation",
      "Uses TULIP terminology or Reformed/Calvinist language"
    ],
    filterContent: `## THEOLOGICAL LENS: Independent Baptist

### Scripture
The Bible is inerrant, infallible, preserved, and fully authoritative. Many Independent Baptists prefer KJV, but remain translation-flexible. Use literal-historical-grammatical interpretation. Strong emphasis on Scripture clarity and direct teaching.

### God
God is sovereign, but sovereignty is framed alongside genuine human responsibility. Rejects meticulous determinism. God desires all people to be saved.

### Salvation
- Election typically understood as corporate or based on foreknowledge; strong emphasis on "whosoever will may come"
- Unlimited Atonement: Christ died for the sins of all people everywhere
- The Spirit convicts, but grace is resistible; conversion is a personal decision
- Regeneration follows faith and repentance
- Eternal Security: Once saved, always saved

### Holy Spirit
The Spirit convicts, indwells, sanctifies, and seals believers. Overwhelmingly non-charismatic; extraordinary gifts viewed as ceased.

### Dispensationalism
Strong lean toward classic or revised dispensationalism. Israel and the Church are distinct. Prophetic passages interpreted literally.

### Church
Local church autonomy is absolute. Congregational governance, often pastor-led. No denominational oversight. Strong emphasis on soul-winning, missions, and church planting.

### Eschatology
Strong tendency toward Premillennialism and Pre-tribulational rapture.

### Tone
Clear, direct, evangelistic, Scripture-first. Practical application emphasized. Conservative, traditional moral framing. Encouraging, not academic.`
  },

  // -------------------------------------------------------------------------
  // 6. MISSIONARY BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "missionary-baptist",
    name: "Missionary Baptist",
    shortName: "MB",
    displayOrder: 6,
    isDefault: false,
    summary: "A conservative, evangelistic, missions-driven doctrine emphasizing believer's baptism, local church autonomy, unlimited atonement, personal response to the gospel, eternal security, dispensational leanings, non-charismatic worship, and practical Christian living rooted in Scripture.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    avoidTerminology: [
      "Total Depravity",
      "Total Inability",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "meticulous sovereignty",
      "determinism",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity capable of responding to God",
      "Unconditional Election": "election based on foreknowledge / whosoever will",
      "Limited Atonement": "Christ died for all people",
      "Irresistible Grace": "grace can be resisted; salvation involves genuine response",
      "regeneration precedes faith": "regeneration follows faith and repentance",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Promotes Calvinistic unconditional election or irresistible grace",
      "Suggests salvation can be lost or earned",
      "Introduces charismatic gifts as normative for today",
      "Undermines believer's baptism, church autonomy, or missions focus",
      "Proposes replacement theology or denies Israel/church distinction",
      "Suggests universalism, liberal theology, or works-based salvation",
      "Uses TULIP terminology or Reformed language"
    ],
    filterContent: `## THEOLOGICAL LENS: Missionary Baptist

### Scripture
The Bible is inerrant, infallible, verbally inspired, preserved, authoritative, and the final rule of faith and practice. Rejects higher criticism and modernist reinterpretation.

### God
God is sovereign but exercises sovereignty consistent with human responsibility. Rejects deterministic interpretations. God desires all people to be saved.

### Salvation
- Election understood primarily as corporate, Christ-centered, or foreknowledge-based
- Unlimited Atonement: Christ died for all people; salvation provided universally but applied personally through faith
- The Holy Spirit convicts and calls; grace can be resisted
- Regeneration follows faith and repentance, not before
- Eternal Security: True salvation cannot be lost

### Holy Spirit
The Spirit convicts, regenerates, indwells, seals, sanctifies, and empowers. Charismatic expressions rejected as normative.

### Church
Local church is fully autonomous, self-governing, and independent. Strong Landmark influence in some contexts. Believer's baptism by immersion.

### Missions
Missionary Baptists are named for their commitment to missions. Strong emphasis on personal evangelism, local and global missions, discipleship, and church planting.

### Tone
Clear, evangelistic, practical, warm, and accessible. Emphasis on missions, discipleship, and spiritual growth. Avoid academic abstraction.`
  },

  // -------------------------------------------------------------------------
  // 7. GENERAL BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "general-baptist",
    name: "General Baptist",
    shortName: "GB",
    displayOrder: 7,
    isDefault: false,
    summary: "A warm, evangelistic, Arminian Baptist doctrinal baseline emphasizing universal atonement, human freedom, prevenient grace, believer's baptism, local church autonomy, eternal security (modern view), missions, and practical Christian living rooted in Scripture.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-teal-100 text-teal-800 border-teal-200',
    avoidTerminology: [
      "Total Depravity",
      "Total Inability",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "meticulous sovereignty",
      "determinism",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "fallen humanity able to respond to prevenient grace",
      "Unconditional Election": "election is conditional, based on God's foreknowledge of faith",
      "Limited Atonement": "Christ died for all people without exception",
      "Irresistible Grace": "prevenient grace--God empowers but does not coerce",
      "regeneration precedes faith": "regeneration follows repentance and faith",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Promotes unconditional election or irresistible grace",
      "Suggests salvation is coerced or predetermined without human freedom",
      "Advocates charismatic signs as normative",
      "Undermines believer's baptism or local church autonomy",
      "Promotes universalism, liberal theology, or works-based salvation",
      "Asserts loss of salvation (use eternal security unless Historic General Baptist selected)",
      "Uses TULIP terminology or Calvinist language"
    ],
    filterContent: `## THEOLOGICAL LENS: General Baptist

### Scripture
The Bible is inspired, inerrant, authoritative, sufficient, and fully trustworthy. Use literal-historical-grammatical interpretation with emphasis on clarity and simplicity.

### God
God is sovereign but His sovereignty does not override human free will. God desires all people to be saved.

### Salvation
- Election is conditional, based on God's foreknowledge of faith; God elects "in Christ"
- Unlimited Atonement: Christ died for all people without exception
- Prevenient grace--God empowers all people to believe but does not coerce
- Regeneration follows repentance and faith
- Eternal Security (modern view): salvation cannot be lost once genuinely received

### Holy Spirit
The Spirit convicts, regenerates, indwells, sanctifies, seals, and empowers. Most General Baptists are non-charismatic.

### Church
Local church autonomy is essential. Congregational governance. Free and voluntary cooperation with associations.

### Ethics
Emphasis on holiness, obedience, prayer, Scripture engagement. Marriage between one man and one woman. Sanctity of human life.

### Tone
Warm, evangelistic, accessible, Scripture-grounded. Practical, encouraging, and application-focused. Avoid Reformed confessional language.`
  },

  // -------------------------------------------------------------------------
  // 8. FREE WILL BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "free-will-baptist",
    name: "Free Will Baptist",
    shortName: "FWB",
    displayOrder: 8,
    isDefault: false,
    summary: "A warm, evangelistic, holiness-focused, Arminian Baptist doctrinal profile emphasizing universal atonement, genuine human free will, prevenient grace, conditional security, believer's baptism, three ordinances (baptism, Lord's Supper, foot washing), local church autonomy, and a life of obedience empowered by the Holy Spirit.",
    securityDoctrine: 'conditional',
    tulipStance: 'anti',
    badgeClass: 'bg-violet-100 text-violet-800 border-violet-200',
    avoidTerminology: [
      "Total Depravity",
      "Total Inability",
      "Unconditional Election",
      "Limited Atonement",
      "Particular Redemption",
      "Irresistible Grace",
      "Effectual Calling",
      "TULIP",
      "the elect",
      "sovereign election",
      "monergism",
      "regeneration precedes faith",
      "ordained to salvation",
      "once saved always saved",
      "eternal security",
      "meticulous sovereignty",
      "determinism",
      "perseverance of the saints",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "Total Depravity": "humans retain God-given capacity to respond to grace",
      "Unconditional Election": "election is conditional, based on God's foreknowledge of who will believe",
      "Limited Atonement": "Christ died for every person / general atonement",
      "Irresistible Grace": "prevenient grace enables but does not compel belief",
      "regeneration precedes faith": "faith and repentance precede regeneration",
      "eternal security": "conditional security--salvation can be forfeited by persistent unbelief",
      "perseverance of the saints": "continued faith is necessary; apostasy is possible",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Teaches unconditional election or irresistible grace",
      "Promotes eternal security (Free Will Baptists teach conditional security)",
      "Suggests charismatic gifts as normative",
      "Undermines the ordinance of foot washing",
      "Suggests salvation is purely works-based or self-generated",
      "Introduces universalism, liberal theology, or determinism",
      "Uses TULIP terminology or Calvinist language"
    ],
    filterContent: `## THEOLOGICAL LENS: Free Will Baptist

### Scripture
The Bible is inspired, inerrant, infallible, authoritative, and sufficient. Interpreted using literal-historical-grammatical methods.

### God
God is sovereign but exercises sovereignty without negating human freedom. God genuinely desires all people to be saved.

### Salvation
- Election is conditional, based on God's foreknowledge of who will freely believe
- General/Unlimited Atonement: Christ died for every person
- Prevenient grace enables all people to believe without compelling belief
- Faith and repentance precede regeneration
- CONDITIONAL SECURITY: Salvation can be forfeited by persistent, willful unbelief. Apostasy is possible but never accidental--requires conscious, ongoing rejection of Christ.

### Holy Spirit
The Spirit convicts, calls, regenerates, indwells, sanctifies, and empowers. Non-charismatic--tongues and sign gifts are not normative. Holiness strongly emphasized.

### Three Ordinances
1. Baptism: believers only, immersion
2. Lord's Supper: memorial, symbolic
3. Foot Washing: considered an ordinance taught by Jesus (John 13), practiced as humility and service

### Church
Congregational, local church autonomy. Strong emphasis on discipleship, holiness, and community accountability.

### Ethics
Holiness is central: moral purity, humility, separation from sinful practices. Marriage one man and one woman. Sanctity of life.

### Tone
Warm, evangelistic, holiness-oriented, and practical. Clear moral application. Avoid Reformed confessional jargon.`
  },

  // -------------------------------------------------------------------------
  // 9. PRIMITIVE BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "primitive-baptist",
    name: "Primitive Baptist",
    shortName: "PB",
    displayOrder: 9,
    isDefault: false,
    summary: "A deeply Calvinistic, predestinarian, Old School Baptist doctrinal identity emphasizing unconditional election, particular redemption, regeneration without means, absolute security, a cappella worship, local church autonomy, foot washing, and simple, experiential Christian living rooted in Scripture.",
    securityDoctrine: 'perseverance',
    tulipStance: 'pro',
    badgeClass: 'bg-rose-100 text-rose-800 border-rose-200',
    avoidTerminology: [
      "unlimited atonement",
      "Christ died for all",
      "general atonement",
      "prevenient grace",
      "resistible grace",
      "faith causes regeneration",
      "decision for Christ",
      "accept Christ",
      "free will",
      "human ability to believe",
      "altar call",
      "sinner's prayer",
      "mission boards",
      "denominational programs",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "unlimited atonement": "particular redemption / Christ died for the elect",
      "Christ died for all": "Christ died effectually for His people",
      "free will": "human responsibility under God's sovereign decree",
      "decision for Christ": "evidence of regeneration already accomplished by God",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [
      "unconditional election",
      "particular redemption",
      "regeneration by God alone",
      "irresistible grace",
      "total depravity",
      "perseverance of the saints",
      "sovereign grace"
    ],
    guardrails: [
      "Teaches that faith causes regeneration (Primitive Baptists teach regeneration precedes faith)",
      "Suggests universal atonement or conditional election",
      "Promotes mission boards, denominational programs, or institutional fundraising",
      "Introduces charismatic gifts, contemporary worship trends, or entertainment elements",
      "Encourages altar calls, 'decisions for Christ,' or methods-based evangelism",
      "Suggests salvation can be lost",
      "Promotes prosperity theology, liberal theology, or works-based salvation"
    ],
    filterContent: `## THEOLOGICAL LENS: Primitive Baptist

### Scripture
The Bible is inspired, inerrant, authoritative, preserved, and the sole rule of faith and practice. Interpreted within the Old School Baptist tradition.

### God
God is absolutely sovereign over all things. His decrees are eternal and unchangeable. Everything happens according to God's predetermined will. Salvation is entirely God's work.

### Salvation
- Unconditional Election: God chose His people before time based solely on His will
- Particular Redemption: Christ died only for the elect; the atonement is fully effective
- Regeneration occurs directly by God, without human means (no preaching required)
- Regeneration may occur long before conscious faith
- The gospel "in time" instructs and comforts those already spiritually alive
- Faith is evidence of regeneration, not the cause of it
- Absolute security of the eternally elect

### Holy Spirit
The Spirit regenerates without human means. Indwells, comforts, sanctifies, and guides. No charismatic gifts or modern revelations.

### Three Ordinances
1. Baptism: believers only, immersion, testimony of obedience
2. Lord's Supper: memorial ordinance
3. Foot Washing: required ordinance from John 13, symbol of humility

### Church
Local church autonomy, strictly congregational. No boards, conventions, mission societies, or institutional oversight. Strong emphasis on simplicity and experiential faith.

### Worship
A cappella congregational singing (no instruments). Simple, reverent, Scripture-centered. Emphasis on experiential preaching by Spirit-led elders.

### Missions
Traditionally non-missionary; reject organized mission boards. Evangelism is personal, informal, Spirit-led. God's elect will be saved regardless of human methods.

### Tone
Warm, experiential, reverent, Scripture-saturated. Avoid institutional language. Emphasize God's sovereignty and experiential assurance.`
  },

  // -------------------------------------------------------------------------
  // 10. REFORMED BAPTIST
  // -------------------------------------------------------------------------
  {
    id: "reformed-baptist",
    name: "Reformed Baptist",
    shortName: "RB",
    displayOrder: 10,
    isDefault: false,
    summary: "A confessional, sovereign-grace, 1689-aligned theological baseline emphasizing God's exhaustive sovereignty, unconditional election, particular redemption, irresistible grace, covenant theology, plurality of elders, strict congregationalism, and reverent Scripture-regulated worship.",
    securityDoctrine: 'perseverance',
    tulipStance: 'pro',
    badgeClass: 'bg-secondary-light text-secondary border-secondary/20',
    avoidTerminology: [
      "unlimited atonement",
      "Christ died for all",
      "general atonement",
      "prevenient grace",
      "resistible grace",
      "faith precedes regeneration",
      "human decision saves",
      "free will to believe",
      "conditional election",
      "foreseen faith",
      "synergism",
      "conditional security",
      "can lose salvation"
    ],
    preferredTerminology: {
      "unlimited atonement": "particular redemption / definite atonement",
      "Christ died for all": "Christ died effectually for the elect",
      "faith precedes regeneration": "regeneration precedes faith",
      "free will": "human responsibility under divine sovereignty",
      "conditional election": "unconditional election based on God's sovereign will"
    },
    requiredTerminology: [
      "unconditional election",
      "particular redemption",
      "irresistible grace",
      "total depravity",
      "perseverance of the saints",
      "effectual calling",
      "sovereign grace",
      "covenant theology",
      "regeneration precedes faith"
    ],
    guardrails: [
      "Denies unconditional election or irresistible grace",
      "Suggests salvation is based on human decision or foreseen merit",
      "Promotes unlimited atonement, synergism, or conditional security",
      "Undermines covenant theology, the Regulative Principle, or confessional boundaries",
      "Supports universalism, liberal theology, prosperity gospel, or works-based salvation"
    ],
    filterContent: `## THEOLOGICAL LENS: Reformed Baptist (1689 LBCF)

### Scripture
Scripture is inerrant, infallible, sufficient, authoritative, and the only rule for faith and practice. Interpreted using historical-grammatical methods within the confessional Reformed framework.

### God
God exercises meticulous and exhaustive sovereignty over all creation. God ordains all things that come to pass, including salvation.

### Salvation
- Unconditional Election based solely on God's sovereign will; individual, eternal, gracious
- Particular Redemption (Limited Atonement): Christ's death sufficient for all, efficient only for the elect
- Irresistible Grace: the Spirit effectually calls the elect
- Regeneration precedes faith; saving faith is enabled and guaranteed by the Spirit
- Justification by grace alone through faith alone in Christ alone
- Perseverance of the Saints: those truly saved will persevere in holiness

### Covenant Theology
Affirms classic Reformed Covenant Theology: Covenant of Redemption, Covenant of Works, Covenant of Grace. Christ is the fulfillment of all covenants.

### Holy Spirit
The Spirit regenerates, effectually calls, sanctifies, and preserves the elect. Extraordinary charismatic gifts treated cautiously or viewed as ceased.

### Church
Strict congregationalism with plurality of elders. Church membership requires credible profession and baptism. Church discipline is essential.

### Worship
Regulative Principle: only what Scripture commands is permitted in corporate worship. Emphasis on reverence, psalms/hymns, expositional preaching.

### Tone
Doctrinally precise, reverent, confessional language. Avoid pragmatism. Focus on God's sovereignty, Christ's work, and transformation through Scripture.`
  },

  {
    id: "cbf",
    name: "Cooperative Baptist Fellowship",
    shortName: "CBF",
    displayOrder: 11,
    isDefault: false,
    summary: "Affirms Christ's lordship, Scripture's authority, the priesthood of all believers, local church autonomy, women and men in all ministry roles, religious liberty, and cooperative mission through word and deed.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-sky-100 text-sky-800 border-sky-200',
    avoidTerminology: [
      // CBF rejects binding confessions as doctrinal authority
      "Baptist Faith and Message",
      "BF&M",
      "confession requires",
      "our confession states",
      "denominational authority",
      "convention authority",
      "convention requires",
      // CBF affirms women in all ministry roles
      "the pastor (he)",
      "the teacher (he)",
      "he will lead",
      "his congregation",
      "male leadership only",
      "men only may",
      "restricted to men",
      // CBF mission is evangelism AND social witness
      "evangelism only",
      "souls only",
      "personal salvation only",
      "social gospel",
      // CBF polity is cooperative autonomy
      "the denomination requires",
      "denominational mandate",
      "the convention mandates",
      "church body authority over local church",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "BF&M requires": "Scripture teaches",
      "the confession states": "the Bible teaches",
      "denominational position": "the historic Baptist commitment",
      "the pastor (he)": "the pastor",
      "the teacher (he)": "the teacher",
      "his congregation": "their congregation",
      "men in ministry": "women and men in ministry",
      "evangelism alone": "evangelism and embodied witness",
      "saving souls": "proclaiming good news and serving others",
      "the denomination requires": "cooperative Baptist churches affirm",
      "convention authority": "local church discernment",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Cites the Baptist Faith and Message or any Baptist confession as binding authority for CBF content",
      "Assumes creedal or confessional uniformity rather than interpretation under the Holy Spirit",
      "Restricts ministry or leadership roles to men, or uses male-only language for pastors and teachers",
      "Frames mission as evangelism only or dismisses social witness as mere social gospel",
      "Implies denominational or convention authority over the autonomous local church",
      "Uses TULIP terminology or Calvinist/Reformed language",
      "Uses sacramental language such as sacrament or Eucharist instead of Baptist ordinance terms"
    ],
    filterContent: `## THEOLOGICAL LENS: Cooperative Baptist Fellowship

The Cooperative Baptist Fellowship (CBF) is a community of Baptist Christians shaped by the historic Baptist freedoms. Content must reflect these commitments without imposing creedal uniformity.

### The Four Freedoms
- Bible Freedom: Scripture is central and authoritative; each believer interprets it responsibly under the guidance of the Holy Spirit, without a binding creed.
- Soul Freedom: every believer has competency and freedom before God; faith is uncoerced and personal.
- Church Freedom: each local congregation is autonomous and self-governing under the lordship of Christ.
- Religious Freedom: full liberty of conscience for all; church and state remain separate.

### Scripture
The Bible is inspired and authoritative, the trustworthy guide for faith and practice. CBF teachers interpret Scripture under the Holy Spirit's guidance without binding creed or confession. Do not cite the Baptist Faith and Message or any other Baptist confession as authoritative for CBF lesson content.

### God
There is one God, eternally Father, Son, and Holy Spirit -- holy, loving, sovereign, and present. Jesus Christ is Lord; His lordship is the center of Christian faith and discipleship.

### Salvation
Salvation is by grace through faith in Jesus Christ. CBF does not enforce a single position on the security of the believer; soul freedom means congregations and individuals hold this conviction without creedal mandate. Frame salvation in warm, biblical, grace-centered terms.

### Holy Spirit
The Holy Spirit guides interpretation, convicts, comforts, gifts, and empowers believers for ministry and witness. Do not assume creedal or confessional uniformity.

### Church and Ministry
Affirm local church autonomy; do not imply denominational or convention authority over the local congregation. CBF affirms the priesthood of all believers. Women and men serve equally in all aspects of church leadership and ministry. Use gender-inclusive language for all ministry and leadership roles; never restrict pastoral or teaching roles to men.

### Mission
Frame mission as both proclamation and embodied witness. Evangelism and justice are not in tension for CBF; both express the Great Commission. Mission is cooperative -- churches partner together for missions and ministry through word and deed.

### Ordinances
Two ordinances: believer's baptism by immersion and the Lord's Supper as a symbolic memorial. Use Baptist ordinance language: ordinance not sacrament, Lord's Supper not Eucharist.

### Ethics
Believers are called to faithful, compassionate, Christlike living, marked by love of God and neighbor, justice, mercy, and service to others.

### Tone
Warm, pastoral, thoughtful, and inclusive. Honor freedom of conscience, cooperative spirit, and the dignity of every believer. Avoid creedal rigidity and partisan denominational language.`
  },

  // -------------------------------------------------------------------------
  // 12. REGULAR BAPTIST (GARBC)
  // -------------------------------------------------------------------------
  {
    id: "regular-baptist-garbc",
    name: "Regular Baptist (GARBC)",
    shortName: "GARBC",
    displayOrder: 12,
    isDefault: false,
    summary: "The General Association of Regular Baptist Churches (GARBC), whose Articles of Faith are the doctrinal standard. Hallmarks: verbal-plenary inspiration and biblical inerrancy, cessationism, literal six-day creation with a historical Adam, eternal security, two ordinances by immersion, autonomous local-church congregationalism, biblical personal and ecclesiastical separation, Israel distinct from the church, and dispensational premillennial / pretribulational eschatology.",
    securityDoctrine: 'eternal',
    tulipStance: 'anti',
    badgeClass: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    avoidTerminology: [
      "replacement theology",
      "theistic evolution",
      "speaking in tongues",
      "lose your salvation",
      "sprinkling",
      // CRITICAL: Baptists use "ordinance" not "sacrament" (except Reformed Baptist)
      "sacrament",
      "sacraments",
      "Eucharist"
    ],
    preferredTerminology: {
      "communion": "the Lord's Supper",
      "christening": "believer's baptism",
      // CRITICAL: Baptist terminology for ordinances
      "sacrament": "ordinance",
      "sacraments": "ordinances",
      "Eucharist": "Lord's Supper"
    },
    requiredTerminology: [],
    guardrails: [
      "Presents tongues, modern prophecy, words of knowledge, or other sign gifts as normative Christian experience",
      "Presents theistic evolution or an allegorical or mythical reading of Genesis as acceptable",
      "Denies a historical Adam and Eve as the first parents of the entire human race",
      "Presents gender as anything other than God's fixed binary design of male and female, or marriage as anything other than one man and one woman",
      "Suggests a truly born-again believer can lose salvation",
      "Presents replacement theology or supersessionism, or identifies the church as the new Israel or spiritual Israel",
      "Frames amillennialism, postmillennialism, or post-tribulationism as this profile's eschatology",
      "Teaches annihilationism or universalism, or denies the everlasting conscious punishment of the lost",
      "Presents biblical separation as legalism to apologize for rather than as obedience to God",
      "Presents baptism by sprinkling, pouring, or infant baptism as valid"
    ],
    filterContent: `## THEOLOGICAL LENS: Regular Baptist (GARBC)

This profile follows the Articles of Faith of the General Association of Regular Baptist Churches (GARBC). Content must reflect these commitments faithfully.

### Scripture
Verbal, plenary inspiration of the 66 books as originally written; infallible and inerrant in all matters of which it speaks; the supreme standard for all conduct, creed, and opinion.

### God
One true God in three persons -- Father, Son, and Holy Spirit -- equal in every divine perfection.

### Holy Spirit and Cessationism
The Spirit convicts, regenerates, seals, indwells, guides, and sanctifies. The sign and revelatory gifts (tongues, prophecy, sign-healings) have fulfilled their purpose and are NOT in operation today. Lessons must never present tongues, modern prophecy, words of knowledge, or sign gifts as normative Christian experience.

### Creation
Literal, historical, direct creation without any evolutionary process; Genesis 1-2 is neither allegory nor myth; historical Adam and Eve as the first parents of the entire human race. Never present theistic evolution or allegorical Genesis readings as acceptable. Gender is God's fixed binary creative design (male and female); marriage is one man and one woman; sexual intimacy belongs only within biblically defined marriage.

### Sin
All people are totally depraved in Adam, sinners by nature and by conduct, under just condemnation.

### Salvation
Divinely initiated and wholly of grace through faith in the Lord Jesus Christ alone; voluntary substitutionary atonement -- Christ bore our sins in His own body on the tree; repentance is a Spirit-prompted change of mind integral to saving faith; the new birth is instantaneous, not a process. Justification is God's judicial declaration based on Christ's imputed righteousness, never works.

### Security
All who are truly born again are kept by God the Father for Jesus Christ. Never suggest a true believer can lose salvation.

### Church
A local church is an organized congregation of immersed believers, autonomous and self-governing, free from hierarchical interference, with Christ as the only Superintendent; officers are pastors and deacons -- godly men per Scripture. Also affirms the unity of all New Testament believers in the Body of Christ. Lessons respect local-church autonomy and congregational polity.

### Ordinances
Two ordinances only. Believer's baptism by SINGLE IMMERSION, under local church authority, prerequisite to church membership. The Lord's Supper commemorates Christ's death until He comes, preceded by solemn self-examination, for immersed believers; the biblical order is baptism first, then the Supper.

### Separation
Obedience to the biblical commands of personal separation from worldliness and ecclesiastical separation from apostasy (2 Cor 6:14-7:1; Rom 16:17; 2 John 9-11). Where relevant, lessons present biblical separation positively as obedience to God, never as legalism to apologize for.

### Civil Government
Divinely appointed; pray for, honor, and obey magistrates except where commands oppose the will of the Lord Jesus Christ.

### Israel
Israel is God's eternal covenant people, distinct from the church; now dispersed, to be regathered and saved as a nation at Christ's second advent. NEVER present replacement theology or supersessionism; never identify the church as the new Israel or spiritual Israel.

### Eschatology
Dispensational premillennialism. Pretribulational rapture of the church, imminent (any-moment); a seven-year Tribulation follows; premillennial return of Christ in power to sit on David's throne and establish His earthly kingdom. Never frame amillennialism, postmillennialism, or post-tribulationism as this profile's view.

### Final States
Everlasting felicity of the saved; everlasting CONSCIOUS suffering of the lost in the Lake of Fire. Never annihilationism or universalism. Satan is a real created person destined for the Lake of Fire.

### Tone
Clear, reverent, Scripture-first, and doctrinally definite. Conservative and separatist in the biblical sense, warm in pastoral application. Avoid charismatic framing, evolutionary concession, and any softening of eternal security or the church/Israel distinction.`
  }
];

// ============================================================================
// BAPTIST TERMINOLOGY GUARDRAILS (SSOT)
// Universal rules that apply to ALL Baptist theology profiles
// These prevent non-Baptist terminology from appearing in generated content
// ============================================================================

/**
 * BAPTIST TERMINOLOGY GUARDRAILS
 *
 * These terms and substitutions apply to ALL Baptist theology profiles.
 * They ensure generated content sounds authentically Baptist, not Catholic,
 * Anglican, Lutheran, or generic Protestant.
 *
 * PRINCIPLE: Baptists use specific terminology that reflects their beliefs
 * about church, ordinances, ministry, and worship. Using incorrect terminology
 * immediately signals "this wasn't written by someone who understands Baptists."
 */
export const BAPTIST_TERMINOLOGY_GUARDRAILS = {
  /**
   * PROHIBITED TERMS
   * These terms should NEVER appear when describing Baptist practices
   * (They may appear when DISCUSSING other traditions)
   */
  prohibitedForBaptistPractices: [
    "ritual",
    "rituals",
    "altar",
    "priest",
    "clergy",
    "laity",
    "mass",
    "holy orders",
    "confirmation",
    "penance",
    "absolution",
    "liturgy",
    "vestments",
    "chalice",
    "host",
    "consecration",
    "transubstantiation",
    "consubstantiation",
    "real presence"
  ],

  /**
   * REQUIRED SUBSTITUTIONS
   * When these terms would naturally occur, substitute with Baptist equivalents
   */
  substitutions: {
    "sacrament": "ordinance",
    "sacraments": "ordinances",
    "Eucharist": "Lord's Supper",
    "Holy Communion": "Lord's Supper",
    "the mass": "the Lord's Supper",
    "altar": "Lord's table",
    "sanctuary": "worship center",
    "nave": "auditorium",
    "chancel": "platform",
    "priest": "pastor",
    "clergy": "ministers",
    "rector": "pastor",
    "vicar": "pastor",
    "ritual": "practice",
    "rituals": "practices",
    "rite": "observance",
    "rites": "observances",
    "liturgy": "order of worship",
    "liturgical": "worship",
    "means of grace": "spiritual disciplines"
  },

  /**
   * CONTEXTUAL EXCEPTIONS
   * When these terms ARE acceptable
   */
  contextualExceptions: [
    {
      term: "ritual",
      acceptable: "When describing OTHER religious traditions or when used negatively to warn against empty formalism",
      example: "Jesus warned against empty rituals that replace genuine faith"
    },
    {
      term: "priest",
      acceptable: "When referring to Old Testament priests, Catholic/Orthodox clergy, or the priesthood of all believers doctrine",
      example: "As believer-priests, we all have direct access to God"
    },
    {
      term: "altar",
      acceptable: "When referring to Old Testament altars or metaphorically to sacrifice/dedication",
      example: "Abraham built an altar to the Lord"
    },
    {
      term: "sacrament",
      acceptable: "ONLY in Reformed Baptist context (1689 LBCF) or when explaining what Baptists DON'T believe",
      example: "Unlike some traditions that view baptism as a sacrament, Baptists understand it as an ordinance"
    }
  ],

  /**
   * BAPTIST-PREFERRED TERMS
   * These terms sound authentically Baptist and should be used freely
   */
  preferredTerms: [
    "ordinance",
    "ordinances",
    "Lord's Supper",
    "believer's baptism",
    "baptism by immersion",
    "pastor",
    "deacon",
    "church member",
    "congregation",
    "worship service",
    "invitation",
    "altar call",
    "decision",
    "profession of faith",
    "believer-priest",
    "soul competency",
    "priesthood of all believers",
    "local church autonomy",
    "cooperative missions",
    "Great Commission",
    "personal relationship with Christ",
    "quiet time",
    "devotional",
    "Bible study",
    "Sunday School",
    "Vacation Bible School",
    "revival",
    "evangelism",
    "witness",
    "testimony"
  ]
} as const;

// ============================================================================
// SOUTHERN BAPTIST SOTERIOLOGICAL GUARDRAILS (SSOT)
// Anti-Calvinist-drift guardrail for the Southern Baptist profiles (BF&M 1963
// and BF&M 2000).
//
// The base SBC profiles already prohibit a handful of Calvinist TERMS
// ("sovereign election", "monergism"), but not the broader Reformed-leaning
// PHRASING the generator tends to default to ("sovereign grace in salvation",
// "He chooses to save whom He will"). That phrasing is technically compatible
// with some Southern Baptists but violates the non-Calvinist mainstream
// represented by the Baptist Faith & Message as a confessional document.
//
// This guardrail prohibits that phrasing at the phrase level and supplies the
// required faith-response framing. It is injected into the AI prompt via
// generateTheologicalGuardrails(), so it reaches all three generators
// (generate-lesson, generate-devotional, and generate-parable through
// ParableGenerator.tsx) -- but only for the profiles in appliesToProfileIds.
// For every other profile it contributes nothing.
// ============================================================================

export const SOUTHERN_BAPTIST_SOTERIOLOGICAL_GUARDRAILS = {
  /**
   * Profiles this guardrail applies to. Both Southern Baptist profiles share the
   * same non-Calvinist soteriology, so both are gated here.
   */
  appliesToProfileIds: [
    "southern-baptist-bfm-1963",
    "southern-baptist-bfm-2000"
  ],

  /**
   * PROHIBITED PHRASES -- must never appear in SBC-profile lessons.
   * Each phrase carries a required replacement. A null replacement means the
   * phrase is prohibited outright with no substitute (do not use the concept).
   */
  prohibitedPhrases: [
    {
      phrase: "sovereign grace in salvation",
      replacement: "God's grace extended to all who respond in faith"
    },
    {
      phrase: "He chooses to save whom He will",
      replacement: "God graciously offers salvation to all who respond in faith"
    },
    {
      phrase: "God sovereignly elects",
      replacement: "God calls all people to salvation through faith"
    },
    {
      phrase: "sovereign election",
      replacement: "God calls all people to salvation through faith"
    },
    {
      phrase: "monergistic",
      replacement: "salvation is God's gift, received through a genuine faith-response"
    },
    {
      phrase: "irresistible grace",
      replacement: null
    },
    {
      phrase: "particular redemption",
      replacement: null
    },
    {
      phrase: "limited atonement",
      replacement: null
    }
  ],

  /**
   * CONDITIONALLY PERMISSIBLE PHRASES -- allowed only in the stated narrow sense,
   * never as the explanation of why a particular individual is saved.
   */
  conditionalPhrases: [
    {
      phrase: "chosen before the foundation of the world",
      permittedOnly: "as general doxology about God's people in Christ -- never as the explanation of why an individual person was saved"
    }
  ],

  /**
   * REQUIRED FRAMING -- the faith-response framing that must shape any salvation
   * language in an SBC-profile lesson.
   */
  requiredFraming: [
    "Center salvation language on the human faith-response. Example: \"Rahab's faith, not God's sovereign selection, is what Scripture commends.\"",
    "Assume or state universal atonement: \"Christ's death is sufficient for all and available to all.\"",
    "Prefer \"whosoever will\" framing when describing the scope of salvation (cf. John 3:16; Romans 10:13).",
    "When describing God's purposes for an individual, use volitional/responsive language -- \"God can use anyone who responds to Him in faith\" -- not \"God chose her for His purposes.\"",
    "Frame a person's inclusion in God's plan (e.g., Rahab in the genealogy of Christ) as the result of their faith response, not as evidence of prior divine election."
  ],

  /**
   * CANONICAL REWRITE -- the exact drift pattern to avoid and the exact pattern
   * to produce in its place, for the Theological Background section.
   */
  canonicalRewrite: {
    avoid: "This passage demonstrates God's sovereign grace in salvation--He chooses to save whom He will, not based on human merit but according to His purposes.",
    use: "This passage demonstrates God's grace available to all who respond in faith--Rahab's story shows that no background, nationality, or past disqualifies a person from receiving salvation through trust in God."
  }
} as const;

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get a theology profile by ID
 */
export function getTheologyProfile(id: string): TheologyProfile | undefined {
  return THEOLOGY_PROFILES.find(profile => profile.id === id);
}

/**
 * Get the default theology profile
 */
export function getDefaultTheologyProfile(): TheologyProfile {
  return THEOLOGY_PROFILES.find(profile => profile.isDefault) || THEOLOGY_PROFILES[0];
}

/**
 * Get profiles sorted by display order
 */
export function getTheologyProfilesSorted(): TheologyProfile[] {
  return [...THEOLOGY_PROFILES].sort((a, b) => a.displayOrder - b.displayOrder);
}

/**
 * Get user-facing profile options (for dropdowns)
 * Returns only id, name, shortName, and summary
 */
export function getTheologyProfileOptions(): Array<{
  id: TheologyProfileId;
  name: string;
  shortName: string;
  summary: string;
  isDefault: boolean;
}> {
  return getTheologyProfilesSorted().map(profile => ({
    id: profile.id,
    name: profile.name,
    shortName: profile.shortName,
    summary: profile.summary,
    isDefault: profile.isDefault
  }));
}

/**
 * Generate Baptist terminology guardrails for AI prompt injection
 * These apply to ALL Baptist theology profiles to ensure authentic Baptist voice
 */
export function generateBaptistTerminologyGuardrails(): string {
  const guardrails = BAPTIST_TERMINOLOGY_GUARDRAILS;

  return `
## BAPTIST TERMINOLOGY GUARDRAILS -- UNIVERSAL COMPLIANCE

These terminology rules ensure generated content sounds authentically Baptist.
Violations immediately signal "this wasn't written by someone who understands Baptists."

### PROHIBITED TERMS (When Describing Baptist Practices)
The following terms must NOT be used to describe what Baptists do or believe:
${guardrails.prohibitedForBaptistPractices.map(term => `- "${term}"`).join('\n')}

### MANDATORY SUBSTITUTIONS
When these terms would naturally occur, use the Baptist equivalent:
${Object.entries(guardrails.substitutions).map(([avoid, use]) => `- Instead of "${avoid}" ? use "${use}"`).join('\n')}

### CONTEXTUAL EXCEPTIONS
These terms ARE acceptable in specific contexts:
- "ritual" - When warning against empty formalism or describing OTHER traditions
- "priest" - When referring to OT priests or explaining "priesthood of all believers"
- "altar" - When referring to OT altars or metaphorically (but NOT Baptist church furniture)
- "sacrament" - ONLY when explaining what Baptists DON'T believe or in Reformed Baptist context

### AUTHENTICALLY BAPTIST LANGUAGE
Use these terms freely - they sound genuinely Baptist:
ordinance, Lord's Supper, believer's baptism, pastor, deacon, congregation,
worship service, invitation, profession of faith, believer-priest,
soul competency, local church autonomy, Great Commission, testimony

### VERIFICATION CHECK
Before outputting content, scan for:
1. Any prohibited term used to describe Baptist practices
2. Any missed substitutions (especially "ritual" or "sacrament")
3. Overly formal/liturgical language that doesn't fit Baptist culture
`;
}

/**
 * Generate the Southern Baptist soteriological guardrail block for AI prompt
 * injection. Returns an empty string for any profile not listed in
 * SOUTHERN_BAPTIST_SOTERIOLOGICAL_GUARDRAILS.appliesToProfileIds, so it is safe
 * to call for every profile. Injected by generateTheologicalGuardrails().
 */
export function generateSouthernBaptistSoteriologicalGuardrails(profileId: string): string {
  const g = SOUTHERN_BAPTIST_SOTERIOLOGICAL_GUARDRAILS;

  if (!(g.appliesToProfileIds as readonly string[]).includes(profileId)) {
    return '';
  }

  const prohibited = g.prohibitedPhrases
    .map(({ phrase, replacement }) =>
      replacement
        ? `- "${phrase}" -- instead use: "${replacement}"`
        : `- "${phrase}" -- PROHIBITED ENTIRELY (do not use the phrase or the concept)`
    )
    .join('\n');

  const conditional = g.conditionalPhrases
    .map(({ phrase, permittedOnly }) => `- "${phrase}" -- permitted ONLY ${permittedOnly}`)
    .join('\n');

  const framing = g.requiredFraming.map(rule => `- ${rule}`).join('\n');

  return `

## SOUTHERN BAPTIST SOTERIOLOGICAL LANGUAGE RULES -- MANDATORY

The Southern Baptist profiles affirm the non-Calvinist mainstream of the Baptist
Faith & Message. Salvation must always be framed around the human faith-response,
never around divine selection of particular individuals. The terminology rules
above are reinforced here at the phrase level and take precedence on any conflict.

### PROHIBITED PHRASES (must never appear in any section)
${prohibited}

### CONDITIONALLY PERMISSIBLE PHRASES
${conditional}

### REQUIRED FRAMING (must shape all salvation language)
${framing}

### CANONICAL REWRITE -- Theological Background section
Do NOT write (Calvinist drift):
"${g.canonicalRewrite.avoid}"

Instead write (faith-response framing):
"${g.canonicalRewrite.use}"
`;
}

/**
 * Generate the theological guardrails block for AI prompt injection
 */
export function generateTheologicalGuardrails(profileId: string): string {
  const profile = getTheologyProfile(profileId) || getDefaultTheologyProfile();
  
  let guardrailsBlock = `
## THEOLOGICAL GUARDRAILS -- MANDATORY COMPLIANCE

**Selected Theology Profile:** ${profile.name}

${profile.filterContent}

---

### TERMINOLOGY RULES
`;

  if (profile.avoidTerminology.length > 0) {
    guardrailsBlock += `
**PROHIBITED TERMINOLOGY (DO NOT USE):**
${profile.avoidTerminology.map(term => `- "${term}"`).join('\n')}
`;
  }

  if (Object.keys(profile.preferredTerminology).length > 0) {
    guardrailsBlock += `
**REQUIRED SUBSTITUTIONS:**
${Object.entries(profile.preferredTerminology).map(([avoid, prefer]) => `- Instead of "${avoid}" ? use "${prefer}"`).join('\n')}
`;
  }

  if (profile.requiredTerminology.length > 0) {
    guardrailsBlock += `
**REQUIRED TERMINOLOGY (MUST USE):**
${profile.requiredTerminology.map(term => `- "${term}"`).join('\n')}
`;
  }

  guardrailsBlock += `
### CONTENT PROHIBITIONS
The generated lesson MUST NOT contain content that:
${profile.guardrails.map(g => `- ${g}`).join('\n')}

### FINAL VERIFICATION
Before outputting the lesson, verify:
1. No prohibited terminology appears in any section
2. Required substitutions are applied consistently
3. ${profile.tulipStance === 'anti' ? 'No TULIP/Calvinist terminology is present' : 'Reformed/TULIP terminology is used appropriately'}
4. Security doctrine reflects: ${profile.securityDoctrine === 'eternal' ? 'Eternal Security (once saved, always saved)' : profile.securityDoctrine === 'conditional' ? 'Conditional Security (salvation can be forfeited through persistent unbelief)' : 'Perseverance of the Saints (the truly elect will persevere)'}
5. Content aligns with the theological lens described above
6. No non-Baptist terminology appears (see Baptist Terminology Guardrails below)
`;

  // Append universal Baptist terminology guardrails
  guardrailsBlock += '\n\n' + generateBaptistTerminologyGuardrails();

  // Append Southern Baptist soteriological guardrails.
  // No-op (empty string) for every profile except the two SBC profiles.
  guardrailsBlock += generateSouthernBaptistSoteriologicalGuardrails(profile.id);

  return guardrailsBlock;
}

// ============================================================================
// EXPORTS FOR BACKWARD COMPATIBILITY
// ============================================================================

// Legacy export for existing code that expects simple array
// Uses sorted order to respect displayOrder
export const THEOLOGY_PROFILE_OPTIONS = getTheologyProfileOptions();


// =============================================================================
// SSOT DEFAULTS AND HELPERS
// =============================================================================

/** Default theology profile ID - used as fallback across the platform */
export const DEFAULT_THEOLOGY_PROFILE_ID = 'baptist-core-beliefs';

/** Default badge class for unknown/missing profiles */
export const DEFAULT_BADGE_CLASS = 'bg-muted text-foreground border-border';

/** Get badge CSS class for a theology profile ID */
export const getProfileBadgeClass = (profileId: string): string => {
  const profile = THEOLOGY_PROFILES.find(p => p.id === profileId);
  return profile?.badgeClass ?? DEFAULT_BADGE_CLASS;
};
