// ============================================================================
// BACKEND MIRROR: Trial Feature Configuration
// SYNCED FROM: src/constants/trialConfig.ts
// DO NOT EDIT THIS FILE - Edit the frontend SSOT and sync
// ============================================================================

// ----------------------------------------------------------------------------
// TRIAL CONFIGURATION
// ----------------------------------------------------------------------------

export const TRIAL_CONFIG = {
  enabled: true,
  sectionsGranted: 8,
  resetPeriod: 'monthly' as const,
  appliesTo: ['free'] as const,
  excludeBetaGraduates: false,
  adminCanGrant: true,
  defaultGrantDays: 30,
  messages: {
    available: {
      title: "Your First Lesson This Month is FREE at Full Quality!",
      description: "Experience all 8 sections of a complete Bible study lesson.",
      cta: "Generate My Free Full Lesson",
    },
    used: {
      title: "You've Used Your Free Full Lesson This Month",
      description: "Your remaining lessons will include 3 core sections.",
      upsell: "Upgrade to Personal ($9/mo) for all 8 sections, every time.",
      cta: "Upgrade Now",
    },
    adminGranted: {
      title: "You've Been Granted a Free Full-Tier Lesson!",
      description: "Enjoy all 8 sections on your next lesson.",
    },
    nextReset: "Your free full lesson resets on the 1st of each month.",
  },
} as const;

// ----------------------------------------------------------------------------
// TRIAL AVAILABILITY LOGIC
// ----------------------------------------------------------------------------

export const isTrialAvailable = (
  lastUsed: Date | string | null,
  grantedUntil: Date | string | null
): boolean => {
  const now = new Date();
  
  if (grantedUntil) {
    const grantDate = typeof grantedUntil === 'string' ? new Date(grantedUntil) : grantedUntil;
    if (grantDate > now) {
      return true;
    }
  }
  
  if (!lastUsed) {
    return true;
  }
  
  const lastUsedDate = typeof lastUsed === 'string' ? new Date(lastUsed) : lastUsed;
  const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  
  return lastUsedDate < currentMonthStart;
};

export const doesTrialApply = (
  platformMode: string,
  userTier: string
): boolean => {
  if (platformMode !== 'production') {
    return false;
  }
  
  return (TRIAL_CONFIG.appliesTo as readonly string[]).includes(userTier);
};

export const getNextTrialReset = (): Date => {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth() + 1, 1);
};
