// ============================================================================
// ComparePage.tsx -- Public "BLS vs. The Competition" comparison page
//
// Route: /compare (public, unauthenticated -- registered outside ProtectedRoute
// in App.tsx, mirroring /curriculum-evaluation).
//
// Content SSOT: src/config/comparisonConfig.ts (COMPARISON_PAGE + COMPETITORS).
// Branding: strict BLS design system only -- Tailwind classes mapped to the
// CSS variables in src/index.css (generated by src/config/branding.ts).
// No new colors, hex codes, or fonts. The prototype palette is NOT used.
//
// Detail view: shadcn Dialog (the most-used overlay in BLS; Radix gives focus
// trap, Esc-to-close, aria-modal, and focus restoration for free).
//
// Marks (Rule #22): lucide-react icons, each paired with sr-only state text:
//   competitor true  -> Check  (text-success)   "Included"
//   competitor false -> X      (text-destructive)"Not included"
//   competitor partial -> Minus(text-warning)   "Partial"
//   bls always true  -> Check  (text-success)   "Included"
// ============================================================================

import { useEffect, useState } from 'react';
import { Check, X, Minus, ArrowRight } from 'lucide-react';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import {
  COMPARISON_PAGE,
  COMPETITORS,
  type Competitor,
  type CompetitorMark,
} from '@/config/comparisonConfig';

// ----------------------------------------------------------------------------
// SEO head helper (mirrors src/pages/ChurchPlantReport.tsx)
// ----------------------------------------------------------------------------
function setMetaDescription(content: string) {
  let tag = document.querySelector('meta[name="description"]') as HTMLMetaElement | null;
  if (!tag) {
    tag = document.createElement('meta');
    tag.setAttribute('name', 'description');
    document.head.appendChild(tag);
  }
  tag.setAttribute('content', content);
}

// ----------------------------------------------------------------------------
// Comparison mark cell
// ----------------------------------------------------------------------------
function Mark({ state }: { state: CompetitorMark }) {
  if (state === 'partial') {
    return (
      <span className="inline-flex items-center justify-center">
        <Minus className="h-5 w-5 text-warning" aria-hidden="true" />
        <span className="sr-only">Partial</span>
      </span>
    );
  }
  if (state) {
    return (
      <span className="inline-flex items-center justify-center">
        <Check className="h-5 w-5 text-success" aria-hidden="true" />
        <span className="sr-only">Included</span>
      </span>
    );
  }
  return (
    <span className="inline-flex items-center justify-center">
      <X className="h-5 w-5 text-destructive" aria-hidden="true" />
      <span className="sr-only">Not included</span>
    </span>
  );
}

// ----------------------------------------------------------------------------
// Head-to-head table (inside the dialog)
// ----------------------------------------------------------------------------
function HeadToHeadTable({ competitor }: { competitor: Competitor }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full border-collapse text-sm">
        <caption className="sr-only">
          Feature comparison between {competitor.name} and BibleLessonSpark
        </caption>
        <thead>
          <tr className="border-b border-border">
            <th scope="col" className="py-2 pr-3 text-left font-semibold text-foreground">
              Capability
            </th>
            <th scope="col" className="px-3 py-2 text-center font-semibold text-foreground">
              {competitor.name}
            </th>
            <th scope="col" className="px-3 py-2 text-center font-semibold text-primary">
              BibleLessonSpark
            </th>
          </tr>
        </thead>
        <tbody>
          {competitor.comparisonTable.map((row) => (
            <tr key={row.capability} className="border-b border-border/60">
              <th scope="row" className="py-2 pr-3 text-left font-normal text-muted-foreground">
                {row.capability}
              </th>
              <td className="px-3 py-2 text-center">
                <Mark state={row.competitor} />
              </td>
              <td className="px-3 py-2 text-center">
                <Mark state={row.bls} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ----------------------------------------------------------------------------
// Page
// ----------------------------------------------------------------------------
export default function ComparePage() {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  // SEO: set title + meta description; restore on unmount.
  useEffect(() => {
    const previousTitle = document.title;
    const previousDescTag = document.querySelector('meta[name="description"]') as HTMLMetaElement | null;
    const previousDesc = previousDescTag ? previousDescTag.getAttribute('content') : null;

    document.title = COMPARISON_PAGE.seo.title;
    setMetaDescription(COMPARISON_PAGE.seo.description);

    return () => {
      document.title = previousTitle;
      if (previousDesc !== null) {
        setMetaDescription(previousDesc);
      }
    };
  }, []);

  const selected = selectedId
    ? COMPETITORS.find((c) => c.id === selectedId) ?? null
    : null;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      <main className="flex-1">
        {/* Hero */}
        <section className="border-b border-border bg-muted/30">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 py-12 sm:py-16 text-center">
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-primary">
              {COMPARISON_PAGE.title}
            </h1>
            <p className="mt-4 text-base sm:text-lg leading-relaxed text-muted-foreground max-w-3xl mx-auto">
              {COMPARISON_PAGE.subtitle}
            </p>
            <p className="mt-6">
              <span className="inline-block rounded-full bg-accent px-4 py-2 text-sm font-semibold text-accent-foreground">
                {COMPARISON_PAGE.pricingBadge}
              </span>
            </p>
          </div>
        </section>

        {/* Card grid */}
        <section className="mx-auto max-w-5xl px-4 sm:px-6 py-12 sm:py-16">
          <div className="mb-8 text-center">
            <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-foreground">
              {COMPARISON_PAGE.sectionHeading}
            </h2>
            <p className="mt-3 text-base leading-relaxed text-muted-foreground">
              {COMPARISON_PAGE.sectionInstruction}
            </p>
          </div>

          <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {COMPETITORS.map((c) => (
              <li key={c.id}>
                <button
                  type="button"
                  onClick={() => setSelectedId(c.id)}
                  aria-label={`Compare BibleLessonSpark with ${c.name}`}
                  className="group flex h-full w-full flex-col rounded-lg border border-border bg-card p-5 text-left shadow-sm transition-colors hover:border-primary focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                >
                  <Badge variant="secondary" className="mb-3 w-fit text-xs">
                    {c.denominationTag}
                  </Badge>
                  <h3 className="text-lg font-semibold text-foreground">{c.name}</h3>
                  <p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">
                    {c.cardDescription}
                  </p>
                  <span className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-primary">
                    View comparison
                    <ArrowRight
                      className="h-4 w-4 transition-transform group-hover:translate-x-0.5"
                      aria-hidden="true"
                    />
                  </span>
                </button>
              </li>
            ))}
          </ul>
        </section>

        {/* Accuracy + trademark footer line */}
        <section className="border-t border-border bg-muted/30">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 py-8 text-center">
            <p className="text-sm font-medium text-foreground">
              {COMPARISON_PAGE.footer.pricingNote}
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              {COMPARISON_PAGE.footer.tagline}
            </p>
            <p className="mt-4 text-xs text-muted-foreground">
              {COMPARISON_PAGE.footer.accuracyNote}
            </p>
            <p className="mt-1 text-xs text-muted-foreground max-w-3xl mx-auto">
              {COMPARISON_PAGE.footer.trademarkNote}
            </p>
          </div>
        </section>
      </main>

      <Footer />

      {/* Head-to-head detail dialog */}
      <Dialog open={selected !== null} onOpenChange={(open) => !open && setSelectedId(null)}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          {selected && (
            <>
              <DialogHeader>
                <DialogTitle className="text-primary">
                  BibleLessonSpark vs. {selected.name}
                </DialogTitle>
                <DialogDescription>{selected.modalSubtitle}</DialogDescription>
              </DialogHeader>

              <p className="text-sm leading-relaxed text-foreground">
                {selected.strengthParagraph}
              </p>

              {/* Legend */}
              <div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
                <span className="inline-flex items-center gap-1">
                  <Check className="h-4 w-4 text-success" aria-hidden="true" /> Included
                </span>
                <span className="inline-flex items-center gap-1">
                  <Minus className="h-4 w-4 text-warning" aria-hidden="true" /> Partial
                </span>
                <span className="inline-flex items-center gap-1">
                  <X className="h-4 w-4 text-destructive" aria-hidden="true" /> Not included
                </span>
              </div>

              <HeadToHeadTable competitor={selected} />
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
