/**
 * generate-css.cjs - SSOT CSS Generator
 * ======================================
 * 
 * Generates src/index.css from the SINGLE SOURCE OF TRUTH colors and fonts.
 * Runs automatically before each build via package.json "prebuild" script.
 * 
 * SSOT FLOW:
 *   BRAND object (below) → generate-css.cjs → index.css → Tailwind → Build
 * 
 * TO CHANGE COLORS/FONTS: Edit the BRAND object below, then rebuild.
 * This is the ONLY place colors and fonts are defined.
 */

const fs = require('fs');
const path = require('path');

// =============================================================================
// SINGLE SOURCE OF TRUTH - ALL BRAND COLORS & TYPOGRAPHY
// =============================================================================
// Edit these values to change colors/fonts across the entire application.
// After editing, run: npm run build (prebuild runs automatically)

const BRAND = {
  // Primary: Forest Green
  primary: '#3D5C3D',
  
  // Secondary: Antique Gold
  secondary: '#D4A74B',
  
  // Accent: Deep Gold
  accent: '#C9A754',
  
  // Destructive: Burgundy (NOT salmon/coral)
  destructive: '#661A33',
  
  // Background: Warm Cream
  background: '#FFFEF9',
  backgroundSecondary: '#FAF8F3',
  
  // Text
  textPrimary: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textMuted: '#9CA3AF',
  
  // Border
  border: '#E5E5E0',
  
  // Success/Warning/Info
  success: '#3D5C3D',
  warning: '#D4A74B',
  info: '#3B82F6',
  
  // ===== TYPOGRAPHY =====
  fontPrimary: '"Poppins", system-ui, sans-serif',
  fontSecondary: '"Merriweather", Georgia, serif',
  fontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&family=Merriweather:wght@400;700&display=swap',
};

// =============================================================================
// HEX TO HSL CONVERSION
// =============================================================================

function hexToHsl(hex) {
  hex = hex.replace(/^#/, '');
  
  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;
  
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      case b:
        h = ((r - g) / d + 4) / 6;
        break;
    }
  }
  
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function adjustLightness(hsl, amount) {
  const parts = hsl.split(' ');
  const h = parts[0];
  const s = parts[1];
  const l = parseInt(parts[2]);
  const newL = Math.max(0, Math.min(100, l + amount));
  return `${h} ${s} ${newL}%`;
}

// =============================================================================
// GENERATE CSS
// =============================================================================

function generateCSS() {
  // Convert all HEX colors to HSL
  const primary = hexToHsl(BRAND.primary);
  const secondary = hexToHsl(BRAND.secondary);
  const accent = hexToHsl(BRAND.accent);
  const destructive = hexToHsl(BRAND.destructive);
  const background = hexToHsl(BRAND.background);
  const backgroundSecondary = hexToHsl(BRAND.backgroundSecondary);
  const textPrimary = hexToHsl(BRAND.textPrimary);
  const textSecondary = hexToHsl(BRAND.textSecondary);
  const textMuted = hexToHsl(BRAND.textMuted);
  const border = hexToHsl(BRAND.border);
  const success = hexToHsl(BRAND.success);
  const warning = hexToHsl(BRAND.warning);
  const info = hexToHsl(BRAND.info);

  return `/**
 * BibleLessonSpark Global Styles
 * ==============================
 * 
 * AUTO-GENERATED by scripts/generate-css.cjs - DO NOT EDIT DIRECTLY
 * 
 * SSOT: To change colors/fonts, edit the BRAND object in scripts/generate-css.cjs
 * Then run: npm run build
 * 
 * Generated: ${new Date().toISOString()}
 * 
 * Color Reference:
 *   Primary (Forest Green): ${BRAND.primary} → ${primary}
 *   Secondary (Antique Gold): ${BRAND.secondary} → ${secondary}
 *   Destructive (Burgundy): ${BRAND.destructive} → ${destructive}
 * 
 * Typography:
 *   Primary Font: ${BRAND.fontPrimary}
 *   Secondary Font: ${BRAND.fontSecondary}
 */

@import url('${BRAND.fontUrl}');

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    /* ===== PRIMARY: Forest Green ${BRAND.primary} ===== */
    --primary: ${primary};
    --primary-foreground: 0 0% 100%;
    --primary-hover: ${adjustLightness(primary, -5)};
    --primary-light: ${adjustLightness(primary, 65)};
    
    /* ===== SECONDARY: Antique Gold ${BRAND.secondary} ===== */
    --secondary: ${secondary};
    --secondary-foreground: 0 0% 10%;
    --secondary-hover: ${adjustLightness(secondary, -6)};
    --secondary-light: ${adjustLightness(secondary, 39)};
    
    /* ===== ACCENT: Deep Gold ${BRAND.accent} ===== */
    --accent: ${accent};
    --accent-foreground: 0 0% 10%;
    
    /* ===== DESTRUCTIVE: Burgundy ${BRAND.destructive} ===== */
    --destructive: ${destructive};
    --destructive-foreground: 0 0% 100%;
    --destructive-light: ${adjustLightness(destructive, 65)};
    
    /* ===== BURGUNDY (aliases for scripture, accents) ===== */
    --burgundy: ${destructive};
    --burgundy-light: ${adjustLightness(destructive, 65)};
    
    /* ===== BACKGROUNDS ===== */
    --background: ${background};
    --foreground: ${textPrimary};
    
    /* ===== CARDS & SURFACES ===== */
    --card: 0 0% 100%;
    --card-foreground: ${textPrimary};
    --popover: 0 0% 100%;
    --popover-foreground: ${textPrimary};
    
    /* ===== MUTED ===== */
    --muted: ${backgroundSecondary};
    --muted-foreground: ${textSecondary};
    
    /* ===== BORDERS & INPUTS ===== */
    --border: ${border};
    --input: ${border};
    --ring: ${primary};
    
    /* ===== SUCCESS/WARNING/INFO ===== */
    --success: ${success};
    --success-light: ${adjustLightness(success, 65)};
    --warning: ${warning};
    --warning-light: ${adjustLightness(warning, 39)};
    --info: ${info};
    --info-light: ${adjustLightness(info, 45)};
    
    /* ===== CHART COLORS ===== */
    --chart-1: ${primary};
    --chart-2: ${secondary};
    --chart-3: ${accent};
    --chart-4: ${destructive};
    --chart-5: ${info};
    
    /* ===== SIDEBAR ===== */
    --sidebar-background: 0 0% 100%;
    --sidebar-foreground: ${textPrimary};
    --sidebar-primary: ${primary};
    --sidebar-primary-foreground: 0 0% 100%;
    --sidebar-accent: ${backgroundSecondary};
    --sidebar-accent-foreground: ${textPrimary};
    --sidebar-border: ${border};
    --sidebar-ring: ${primary};
    
    /* ===== DESIGN TOKENS ===== */
    --radius: 0.5rem;
    --radius-sm: 0.25rem;
    --radius-lg: 0.75rem;
    
    /* ===== SPACING ===== */
    --spacing-xs: 0.25rem;
    --spacing-sm: 0.5rem;
    --spacing-md: 1rem;
    --spacing-lg: 1.5rem;
    --spacing-xl: 2rem;
    --spacing-2xl: 3rem;
    
    /* ===== TYPOGRAPHY ===== */
    --font-primary: ${BRAND.fontPrimary};
    --font-secondary: ${BRAND.fontSecondary};
    --font-size-xs: 0.75rem;
    --font-size-sm: 0.875rem;
    --font-size-base: 1rem;
    --font-size-lg: 1.125rem;
    --font-size-xl: 1.25rem;
    --font-size-2xl: 1.5rem;
    --font-size-3xl: 1.875rem;
    --font-size-4xl: 2.25rem;
    
    /* ===== TRANSITIONS ===== */
    --transition-fast: 150ms ease;
    --transition-normal: 250ms ease;
    --transition-slow: 350ms ease;
    
    /* ===== SECTION SPACING ===== */
    --section-y: 2rem;
    --section-y-lg: 3rem;
    
    /* ===== SHADOWS ===== */
    --shadow-sm: 0 1px 2px 0 hsl(${primary} / 0.05);
    --shadow-md: 0 4px 6px -1px hsl(${primary} / 0.1), 0 2px 4px -1px hsl(${primary} / 0.06);
    --shadow-lg: 0 10px 15px -3px hsl(${primary} / 0.1), 0 4px 6px -2px hsl(${primary} / 0.05);
    
    /* ===== GRADIENTS ===== */
    --gradient-primary: linear-gradient(135deg, hsl(${primary}), hsl(${adjustLightness(primary, 10)}));
    --gradient-secondary: linear-gradient(135deg, hsl(${secondary}), hsl(${adjustLightness(secondary, 9)}));
    --gradient-hero: linear-gradient(135deg, hsl(${adjustLightness(primary, -5)}) 0%, hsl(${primary}) 50%, hsl(${secondary}) 100%);
  }
  
  @media (min-width: 1024px) {
    :root {
      --section-y: 3rem;
      --section-y-lg: 4rem;
    }
  }
  
  .dark {
    --background: 0 0% 10%;
    --foreground: 0 0% 95%;
    --card: 0 0% 12%;
    --card-foreground: 0 0% 95%;
    --popover: 0 0% 12%;
    --popover-foreground: 0 0% 95%;
    --primary: ${adjustLightness(primary, 10)};
    --primary-foreground: 0 0% 100%;
    --secondary: ${adjustLightness(secondary, 9)};
    --secondary-foreground: 0 0% 10%;
    --muted: 0 0% 20%;
    --muted-foreground: 0 0% 65%;
    --accent: ${adjustLightness(accent, 9)};
    --accent-foreground: 0 0% 10%;
    --destructive: ${adjustLightness(destructive, 10)};
    --destructive-foreground: 0 0% 100%;
    --border: 0 0% 20%;
    --input: 0 0% 20%;
    --ring: ${adjustLightness(primary, 10)};
  }
  
  * {
    @apply border-border;
  }
  
  html {
    font-family: ${BRAND.fontPrimary};
  }
  
  body {
    @apply bg-background text-foreground antialiased;
    font-family: ${BRAND.fontPrimary};
    padding-top: env(safe-area-inset-top);
    padding-bottom: env(safe-area-inset-bottom);
  }
  
  ::-webkit-scrollbar {
    width: 6px;
    height: 6px;
  }
  
  ::-webkit-scrollbar-track {
    @apply bg-muted;
  }
  
  ::-webkit-scrollbar-thumb {
    @apply bg-muted-foreground/30 rounded-full;
  }
  
  ::-webkit-scrollbar-thumb:hover {
    @apply bg-muted-foreground/50;
  }
}

@layer components {
  .status-indicator {
    @apply inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm font-medium;
  }

  .status-success {
    @apply bg-success-light text-primary border border-success/20;
  }

  .status-warning {
    @apply bg-warning-light text-secondary-foreground border border-warning/20;
  }

  .status-error {
    @apply bg-destructive-light text-destructive border border-destructive/20;
  }

  .glass {
    @apply backdrop-blur-sm bg-white/80 border border-white/20;
  }

  .gradient-text {
    @apply bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent;
  }

  .scripture-quote {
    @apply pl-4 italic border-l-[3px];
    border-left-color: hsl(var(--burgundy-light));
    font-family: ${BRAND.fontSecondary};
  }

  .footer-accent {
    @apply border-t-2;
    border-top-color: hsl(var(--burgundy));
  }

  .section {
    padding-top: var(--section-y);
    padding-bottom: var(--section-y);
  }

  .section-lg {
    padding-top: var(--section-y-lg);
    padding-bottom: var(--section-y-lg);
  }
}
`;
}

// =============================================================================
// MAIN
// =============================================================================

const outputPath = path.join(__dirname, '../src/index.css');
const cssContent = generateCSS();

fs.writeFileSync(outputPath, cssContent, 'utf8');

console.log('');
console.log('✅ SSOT CSS Generated: src/index.css');
console.log('');
console.log('   Color Reference:');
console.log('   ├── Primary (Forest Green): ' + BRAND.primary + ' → ' + hexToHsl(BRAND.primary));
console.log('   ├── Secondary (Antique Gold): ' + BRAND.secondary + ' → ' + hexToHsl(BRAND.secondary));
console.log('   ├── Destructive (Burgundy): ' + BRAND.destructive + ' → ' + hexToHsl(BRAND.destructive));
console.log('   └── Background (Warm Cream): ' + BRAND.background + ' → ' + hexToHsl(BRAND.background));
console.log('');
console.log('   Typography:');
console.log('   ├── Primary Font: ' + BRAND.fontPrimary);
console.log('   └── Secondary Font: ' + BRAND.fontSecondary);
console.log('');
console.log('   To change: Edit BRAND object in scripts/generate-css.cjs');
console.log('');
