-- Phase E: Add share_token columns for shareable URLs
-- share_token is NULL until the teacher explicitly enables sharing
-- Token is a UUID generated by the frontend and stored here
-- Public Edge Function reads content by token with no auth required

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS share_token UUID UNIQUE DEFAULT NULL;
ALTER TABLE devotionals ADD COLUMN IF NOT EXISTS share_token UUID UNIQUE DEFAULT NULL;
ALTER TABLE lesson_series ADD COLUMN IF NOT EXISTS share_token UUID UNIQUE DEFAULT NULL;

-- Index for fast token lookups (public Edge Function uses these)
CREATE UNIQUE INDEX IF NOT EXISTS lessons_share_token_idx ON lessons(share_token) WHERE share_token IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS devotionals_share_token_idx ON devotionals(share_token) WHERE share_token IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS lesson_series_share_token_idx ON lesson_series(share_token) WHERE share_token IS NOT NULL;
