// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csdtqqddtoureffhtuuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZHRxcWRkdG91cmVmZmh0dXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzE0NTIsImV4cCI6MjA3MzcwNzQ1Mn0._xyzaiU_ki3iHtzUMawcZ64lV6axi0MLnQjtDzOUn1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});